// === DOJO LOCALIZED TEMPLATES: BISAYA ===
// Slot placeholders preserved verbatim; brands/channels/archetypes/actions/difficulties not translated.

import { TemplateFamily } from "./dojo-templates";

export const POOLS_BISAYA = {
  amounts: ["P150", "P250", "P500", "P1,500", "P2,000", "P5,000", "P8,000", "P12,000", "P25,000", "P45,000", "P100,000", "P1,000,000"],
  fakeDomains: [
    "g-cash-verify-ph.top",
    "bdo-secure-login-verify.top",
    "jnt-tracking-ph.site",
    "maya-security-alert.xyz",
    "pagibig-loan-release.site",
    "bit.ly/verify-now",
    "gcash-update.ph-verify.top",
    "smart-rewar-ds.top",
    "shopee-refund-ph.site",
    "gov-ph-tax.site",
  ],
  urgencyTriggers: [
    "naka-lock ang account nimo",
    "mawala ang kwarta nimo sa 24 ka oras",
    "mao na kini ang katapusang higayon nimo",
    "naay case number nga na-file batok nimo",
    "ibalik ang parcel nimo",
    "ikansela ang benefits nimo",
    "naay nakit-an nga unauthorized transfer",
    "ide-deactivate ang SIM nimo",
  ],
  victimProfiles: [
    "Lola sa probinsya",
    "kolehiyala sa Manila",
    "OFW sa Riyadh",
    "tag-iya sa sari-sari store",
    "driver sa jeepney",
    "call-center agent",
    "senior pensioner",
    "gagmay nga online seller",
  ],
  senderLabels: {
    GCASH: "GCash", MAYA: "Maya", GOTYME: "GoTyme", SHOPEEPAY: "ShopeePay",
    BDO: "BDO Alerts", BPI: "BPI", METROBANK: "Metrobank", UNIONBANK: "UnionBank",
    RCBC: "RCBC", LANDBANK: "LandBank", PNB: "PNB", SECURITY_BANK: "Security Bank",
    GLOBE: "Globe", SMART: "Smart", DITO: "DITO", PLDT: "PLDT Home",
    JNT: "J&T Express", LBC: "LBC", NINJAVAN: "Ninja Van", FLASH: "Flash Express",
    SHOPEE: "Shopee", LAZADA: "Lazada", BIR: "BIR", SSS: "SSS", PAGIBIG: "Pag-IBIG",
    PHILHEALTH: "PhilHealth", NBI: "NBI", PNP: "PNP-ACG", CICC: "CICC",
  },
};

export const TEMPLATE_FAMILIES_BISAYA: TemplateFamily[] = [
  {
    family: "ewallet",
    rule: "Lihim ang OTP. DILI mangayo og OTP ang tinuod nga kompanya.",
    brands: ["GCASH", "MAYA", "GOTYME", "SHOPEEPAY"],
    channels: ["sms", "email", "chat", "vishing"],
    correctAction: "verify_in_official_app",
    messageTemplates: [
      "{sender}: {urg} I-reply ang OTP nimo karon para ma-reactivate, o mawala ang kwarta nimo sa 24 ka oras.",
      "{sender} Alerto: {urg}. I-verify sa {domain} o ma-suspend ang account nimo.",
      "{sender}: Naay moabot nga transfer nga {amount}! Mobayad una og gamay nga release fee aron madawat kini.",
      "{sender}: Nakita namo ang suspicious login sa account nimo. I-verify karon sa {domain} o i-lock kini.",
      "{sender}: Ma-expire ang MPIN nimo karon. I-update kini sa {domain} para magamit pa ang wallet nimo.",
      "{sender}: Error sa double refund! Para i-correct, kumpirmaha ang account nimo sa {domain} sa 24 ka oras.",
    ],
    questionTemplates: ["Naay mensahe nga nag-ingon {urg} ug nangayo og OTP. Unsa ang buhaton nimo?", "Naay text nga nag-ingon kinahanglan molihok ka dayon. Unsa ang buhaton nimo?"],
    optionTemplates: {
      correct: ["Ablihi ang tinuod nga {brand} app ug i-check ang account nako."],
      wrong: ["I-reply ang OTP dayon aron luwas ang kwarta nako.", "Tawagi ang numero sa text para ma-verify.", "Bayari ang release fee aron madawat nako ang transfer."],
    },
    correctFeedback: ["Sakto. Gisusi nimo ang tinuod nga {brand} app imbes nga motuo sa text. Ang account nimo ang source of truth, dili ang mensahe."],
    wrongFeedback: [
      "Dili mangayo og OTP ang tinuod nga {brand}. Ang mensahe nga iyan ang scam.",
      "Ang numero nga iyan para sa scammer. Gamita lang ang opisyal nga {official}.",
      "Kung mobayad ka aron makadawat og kwarta, scam kana.",
    ],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "bank",
    rule: "Wala gyuy bangko nga mangayo sa imong OTP o card code.",
    brands: ["BDO", "BPI", "METROBANK", "UNIONBANK", "RCBC", "LANDBANK", "PNB", "SECURITY_BANK"],
    channels: ["email", "sms", "vishing"],
    correctAction: "call_official_hotline",
    messageTemplates: [
      "{sender}: {urg}. I-click ang {domain} para i-verify ang identity nimo karon.",
      "{sender} Fraud Dept: nakit-an ang unauthorized transfer nga {amount}. I-reply ang card details nimo aron ma-reverse.",
      "{sender}: Naka-hold ang account nimo para sa review. I-kumpirma ang identity nimo sa {domain} aron mabalik ang access.",
      "{sender} Security: Naay bag-ong device nga nag-try mag-login. I-approve o i-decline sa {domain}.",
      "{sender}: Sirado na ang card nimo tungod sa inactivity. I-reactivate sa {domain}.",
    ],
    questionTemplates: ["Naay email nga nag-ingon nga naa sa peligro ang account nimo. Unsa ang buhaton nimo?", "Nag-ingon ang nagtawag nga gigamit ang card nimo sa fraud. Unsa ang buhaton nimo?"],
    optionTemplates: {
      correct: ["Ibutang ang tawag, dayon tawagan ang numero sa likod sa card nako.", "Ablihi ang bank app nako ug i-check kung naay tinuod nga alert."],
      wrong: ["Basaha ang card number ug 3-digit code nako aron hunongon ang fraud.", "I-click ang link ug isulod ang login nako aron dili ma-close ang account.", "Basaha balik ang code nga gipadala nila."],
    },
    correctFeedback: ["Sakto. Puwede peke ang caller ID ug sender name. Kanunay tawagon ang tinuod nga {official} number mismo."],
    wrongFeedback: ["Ayaw paghatag og card details o code sa phone o text link. Nahibalo na ang tinuod nga bangko sa card number nimo."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "telco",
    rule: "Dili mangayo ang telco og OTP o ID nimo sa text.",
    brands: ["GLOBE", "SMART", "DITO", "PLDT"],
    channels: ["sms", "chat"],
    correctAction: "verify_in_official_app",
    messageTemplates: [
      "{sender}: Ma-expire na ang points nimo! I-redeem ang {amount} karon sa {domain}.",
      "{sender}: {urg} I-reply ang registered name ug address nimo aron magpabilin ang line nimo.",
      "{sender}: Hapit na ma-expire ang account nimo. I-renew sa {domain} aron mapabilin ang number nimo.",
      "{sender}: Libre nga {amount} load para nimo! I-claim sa {domain} karon.",
      "{sender}: Overdue na ang bill nimo. Bayari ang {amount} sa {domain} aron malikayan ang disconnection.",
    ],
    questionTemplates: ["Naay mensahe nga nagtanyag og points o nagpasidaan sa line nimo. Unsa ang buhaton nimo?"],
    optionTemplates: {
      correct: ["Ablihi ang opisyal nga {brand} app ug i-check didto."],
      wrong: ["I-click ang link ug isulod ang details nako aron mag-redeem.", "I-reply ang tibuok pangalan ug address nako.", "Tawagi ang numero sa text."],
    },
    correctFeedback: ["Sakto. I-check ang opisyal nga {brand} app; ayaw pagsalig sa text link."],
    wrongFeedback: ["Ang pag-reply o pag-click nagsulti sa scammer nga buhi ang number ug details nimo."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "delivery",
    rule: "Bayran ang delivery fee sa tinuod nga app o sa pultahan, dili sa text link.",
    brands: ["JNT", "LBC", "NINJAVAN", "FLASH"],
    channels: ["sms", "chat"],
    correctAction: "compare_tracking",
    messageTemplates: [
      "{sender}: Naka-hold ang parcel nimo para sa unpaid fee nga {amount}. Bayari sa {domain} o ibalik ang package nimo.",
      "{sender}: {urg} Para ma-reschedule ang delivery, mobayad og gamay nga fee sa {domain}.",
      "{sender}: Na-attempt ang delivery pero napakyas. I-reschedule sa {domain} para sa {amount}.",
      "{sender}: Kinahanglan sa package nimo og gamay nga storage fee nga {amount}. Bayari sa {domain}.",
      "{sender}: Dili kompleto ang address nimo. I-confirm sa {domain} o ibalik ang parcel.",
    ],
    questionTemplates: ["Naay mensahe nga nag-ingon naka-hold ang parcel nimo. Unsa ang buhaton nimo?"],
    optionTemplates: {
      correct: ["I-check una ang tinuod nga tracking number sa order app nako."],
      wrong: ["Bayari ang fee aron dili maibalik ang parcel nako.", "Mobayad sa link aron luwas.", "Mag-reply para mag-confirm."],
    },
    correctFeedback: ["Sakto. Gikumpara nimo sa tinuod nga tracking sa order nimo. Kung dili tugma, peke kana."],
    wrongFeedback: ["Gikolekta sa tinuod nga courier ang fee sa pultahan o sa opisyal nga app, dili sa random text link."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "customs",
    rule: "Dili maningil og fee ang customs sa text.",
    brands: ["LBC", "PHILPOST"],
    channels: ["sms", "email"],
    correctAction: "call_official_hotline",
    messageTemplates: [
      "{sender}: Naka-hold sa customs ang package nimo. Bayari ang {amount} clearance fee sa {domain} aron ma-release.",
      "{sender} Customs: Naka-pending sa inspection ang international parcel nimo. Bayari ang {amount} inspection fee sa {domain}.",
      "{sender}: Nakakita ang customs og undeclared items. I-clear sa {domain} para sa {amount}.",
    ],
    questionTemplates: ["Naay customs nga gusto og clearance fee. Unsa ang buhaton nimo?"],
    optionTemplates: {
      correct: ["Tawagon ang opisyal nga hotline sa {sender} aron i-check kung tinuod."],
      wrong: ["Bayari ang fee aron ma-release sa customs ang package nako.", "Mag-reply para mag-confirm."],
    },
    correctFeedback: ["Sakto. Nag-verify ka sa opisyal nga channel. Peke ang text nga customs scam."],
    wrongFeedback: ["Dili maningil og fee ang customs sa text, ug kung wala ka nagpadala og bisan unsa gawas sa nasud, wala nay icle-clear."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "job",
    rule: "Ang trabaho nga mobayad KA aron magtrabaho dili trabaho, scam kana.",
    brands: ["CryptoGlobal", "RemoteHire", "DataEntryPH"],
    channels: ["linkedin", "chat", "email"],
    correctAction: "never_pay_to_work",
    messageTemplates: [
      "Gusto namo ang profile nimo! {amount}/bulan, work from home. I-download kini nga app aron magsugod sa training karon.",
      "Unang task nimo: i-transfer ang {amount} isip refundable performance deposit.",
      "Congratulations! Nakapasar ka sa screening namo. Bayari ang {amount} processing fee sa {domain} aron magsugod.",
      "HR diri: hapit na human ang onboarding nimo. Kumpirmaha sa {domain} para sa {amount} refundable deposit.",
      "Naa ka sa shortlist! I-confirm ang slot nimo sa {domain} sa 24 ka oras.",
    ],
    questionTemplates: ["Naay pangandoy nga trabaho nga nauna nakakita nimo. Unsa ang buhaton nimo?", "Gusto nila og deposit aron magsugod sa trabaho. Unsa ang buhaton nimo?"],
    optionTemplates: {
      correct: ["I-search ang pangalan sa kompanya ug i-check ang tinuod nga website nila.", "Dili. Wala gyuy tinuod nga trabaho nga mangayo og bayad aron magtrabaho."],
      wrong: ["I-download dayon ang app sa dili pa sila mopili og lain.", "Ipadala ang deposit. Nag-ingon sila refundable.", "Ipadala ang tunga ug mangayo og proof."],
    },
    correctFeedback: ["Sakto. Naay verifiable web presence ang tinuod nga kompanya; dili sila magdali-dali nga mag-install og app o mobayad og deposit."],
    wrongFeedback: ["Bayaran KA sa tinuod nga employer. Dili sila mangayo og bayad aron magsugod ka."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "romance",
    rule: "Ayaw pagpadala og kwarta sa taong wala nimo makita og personal.",
    brands: ["DatingApp"],
    channels: ["chat", "vishing"],
    correctAction: "never_send_to_stranger",
    messageTemplates: [
      "Gihigugma tika pero na-stuck ko sa customs ug kinahanglan nako og {amount} aron makita ka. Puwede bang ipadala?",
      "Kinahanglan sa crypto investment nako og {amount} pa aron ma-withdraw, dayon bayaran tika.",
      "Naay problema ko sa airport. Kinahanglan nila og {amount} aron ma-release ang visa nako. Ipadala na karon.",
      "Nag-invest ko para sa atoa, pero kinahanglan nako og {amount} pa aron ma-withdraw ug makaadto nimo.",
      "Na-freeze ang account nako. Puwede bang i-hold ang {amount} para nako hangtod makaabot ko?",
    ],
    questionTemplates: ["Naay taong nakilala nimo online nga nanginahanglan og kwarta karon. Unsa ang buhaton nimo?"],
    optionTemplates: {
      correct: ["Dili. Wala pa nako makita kini nga tao og personal."],
      wrong: ["Ipadala ang kwarta aron dili sila ma-stuck.", "Mangayo una og proof, dayon ipadala.", "Ipadala ang tunga karon."],
    },
    correctFeedback: ["Sakto. Ang romance scammer nagtukod og pagsalig aron mangayo og kwarta. Ayaw pagpadala og kwarta sa wala nimo makita."],
    wrongFeedback: ["Maayo ang pagpangayo og proof, pero ang luwas nga tubag mao ang dili pagpadala og kwarta sa estranghero."],
    archetypes: ["trap", "redirect"],
    difficulties: ["medium", "hard"],
  },
  {
    family: "investment",
    rule: "Ang 'sure profit' nga wala nimo gihangyo kanunay scam.",
    brands: ["Binance", "SureKita", "CryptoPips"],
    channels: ["chat", "email", "sms"],
    correctAction: "ignore_and_report",
    messageTemplates: [
      "Garantisado nga kita! Pag-invest og {amount} karon, doblehon sa usa ka semana. Sure kita, pasok na!",
      "Gidoble sa AI trading app namo ang {amount} sa usa ka bulan. Magsugod na.",
      "Gidoble sa app namo ang {amount} sa 7 ka adlaw. Sugdi ang account nimo karon sa {domain}.",
      "Signal group: garantisado nga {amount} payout sa semana. Sumali sa dili pa magsira.",
      "Kumita og {amount} adlaw-adlaw nga walay risk. Mag-withdraw anytime. Mag-invest karon.",
    ],
    questionTemplates: ["Naay nagsaad og garantisado nga kita. Unsa ang buhaton nimo?"],
    optionTemplates: {
      correct: ["I-ignore ug i-report. Wala gyuy garantisado nga kita."],
      wrong: ["Pag-invest og {amount} aron sulayan.", "Magsugod sa gamay aron i-test.", "I-share sa pamilya aron kumita usab sila."],
    },
    correctFeedback: ["Sakto. Ang 'garantisado nga kita' ang pinakalig-on nga scam signal nga anaa."],
    wrongFeedback: ["Ang bisan kinsa nga nagsaad og garantisado nga kita mokuha sa kwarta nimo, dili i-invest."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "government",
    rule: "Wala gyuy opisina sa gobyerno nga mangayo og fee o OTP sa text.",
    brands: ["BIR", "SSS", "PAGIBIG", "PHILHEALTH", "NBI", "PNP", "CICC"],
    channels: ["sms", "email", "vishing"],
    correctAction: "call_official_hotline",
    messageTemplates: [
      "{sender}: {urg} Bayari ang penalty nimo nga {amount} sa {domain} aron malikayan ang case filing.",
      "{sender}: Ikansela ang benefits nimo gawas kung mag-verify ka sa {domain}.",
      "{sender}: Andam na ang tax refund nimo nga {amount}. I-claim sa {domain} sa dili pa ma-expire.",
      "{sender}: I-update ang records nimo sa {domain} o i-pause ang pension nimo.",
      "{sender}: Naay warrant nga gi-issue batok sa ID nimo. I-resolve sa {domain} aron malikayan ang pag-aresto.",
    ],
    questionTemplates: ["Naay opisina sa gobyerno nga naghulga og penalty sa text. Unsa ang buhaton nimo?"],
    optionTemplates: {
      correct: ["Tawagon ang opisyal nga hotline sa {sender} para ma-verify."],
      wrong: ["Bayari ang penalty aron malikayan ang kaso.", "I-click ang link ug isulod ang details nako.", "Tawagi ang numero sa text."],
    },
    correctFeedback: ["Sakto. Dili maningil ang gobyerno og fee sa text; tawagon ang opisyal nga numero."],
    wrongFeedback: ["Naay opisyal nga channel ang mga ahensya sama sa {sender}. Impersonation ang text."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "quishing",
    rule: "Suspicious ang QR code nga wala nimo gihangyo.",
    brands: ["ParkingPH", "MerchantQR"],
    channels: ["qr"],
    correctAction: "use_official_payment",
    messageTemplates: ["[QR] I-scan para bayaran ang {amount} parking fee. Instant ug secure ang payment.",
      "[QR] I-scan para bayaran ang electric bill nimo. Official partner. {amount} ang bayad.",
      "[QR] Bayari diri ang food delivery nimo. Paspas ug secure.",
      "[QR] I-verify ang parking exit nimo pinaagi sa pag-scan sa code nga kini."],
    questionTemplates: ["Naay QR code nga nagtanyag magbayad sa parking. Unsa ang buhaton nimo?"],
    optionTemplates: {
      correct: ["Pangitaa ang opisyal nga parking sign o mobayad sa machine."],
      wrong: ["I-scan ug mobayad. {amount} lang ra ba.", "I-scan pero i-check ang page sa dili pa mobayad."],
    },
    correctFeedback: ["Sakto. Kanunay gamita ang opisyal nga paagi sa pagbayad, dili ang sticker nga kalit lang nagpakita."],
    wrongFeedback: ["Mahimong nagtudlo ang QR nga iyan sa peke nga payment page nga mangawat sa card nimo."],
    archetypes: ["trap"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "vishing",
    rule: "Puwede peke ang Caller ID. Ibutang ang tawag ug tawagan ang opisyal nga numero.",
    brands: ["BDO", "BPI", "GLOBE", "SMART", "CICC"],
    channels: ["vishing"],
    correctAction: "hang_up_call_official",
    messageTemplates: [
      "Kini ang {sender} fraud department. Gigamit ang card nimo para sa {amount}. Isulti ang card number ug ang code sa likod.",
      "Kinahanglan nato nga i-secure ang account nimo KARON. Magpadala ko og code. Palihug basaha balik.",
      "Kini ang {sender} tech support. Na-hack ang line nimo. Ihatag ang code sa phone nimo.",
      "Nagtawag ko gikan sa {sender}. Naay nag-try nga mo-access sa account nimo. I-confirm ang details nimo.",
      "{sender} agent diri. Para ma-reverse ang fraudulent transfer, kinahanglan nako ang OTP nimo.",
    ],
    questionTemplates: ["Gipakita sa caller ID ang tinuod nga bangko nimo. Unsa ang buhaton nimo?"],
    optionTemplates: {
      correct: ["Ibutang ang tawag, dayon tawagan ang numero sa likod sa card nako."],
      wrong: ["Basaha ang card number nako aron hunongon ang fraud.", "Basaha balik ang code nga gipadala nila.", "Mangayo una og proof kung kinsa sila."],
    },
    correctFeedback: ["Sakto. Puwede peke ang caller ID. Ibutang ang tawag ug tawagan ang tinuod nga numero."],
    wrongFeedback: ["Ayaw pagbasa og code o card details sa taong nagtawag nimo, bisan unsa ka-official ang dating nila."],
    archetypes: ["trap", "redirect"],
    difficulties: ["medium", "hard"],
  },
  {
    family: "sim-pretext",
    rule: "Mag-register sa SIM sa opisyal nga telco channel lamang.",
    brands: ["GLOBE", "SMART", "DITO"],
    channels: ["sms", "chat", "vishing"],
    correctAction: "official_channel_only",
    messageTemplates: ["{sender}: {urg} Mag-re-register sa {domain} o mawala ang SIM nimo.",
      "{sender}: Dili fully registered ang SIM nimo. Kompletoha sa {domain} o putlon ang line nimo.",
      "{sender}: Kinahanglan sa bag-ong SIM rules nga mag-verify ka sa {domain} sa 48 ka oras."],
    questionTemplates: ["Naay mensahe nga nag-ingon ide-deactivate ang SIM nimo. Unsa ang buhaton nimo?"],
    optionTemplates: {
      correct: ["Ablihi ang opisyal nga website o app sa {sender} ug i-check didto."],
      wrong: ["I-click ang link ug isulod ang ID nako.", "Tawagi ang numero sa text."],
    },
    correctFeedback: ["Sakto. Ang SIM registration mahitabo lamang sa opisyal nga telco channel."],
    wrongFeedback: ["Gikolekta sa link nga iyan ang ID nimo. Dili ka i-text sa tinuod nga telco aron mag-register sa random link."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "family-emergency",
    rule: "Gigamit sa scammer ang pangalan sa pamilya aron pahadlokon ka. Tawagi ang tinuod nga naka-save nga numero.",
    brands: ["Child", "Relative"],
    channels: ["sms", "chat", "vishing"],
    correctAction: "call_real_number",
    messageTemplates: [
      "Mom/Dad, ako kini. Nabasag ang phone nako. Ipadala ang {amount} sa GCash nga kini. Palihug ayaw pagtawag, nabasag ang phone nako.",
      "Ako kini, ang anak nimo. Naa ko sa ospital. Kinahanglan sa ospital og {amount}. Palihug ipadala sa numero nga kini.",
      "Lola, naay problema ko sa pulis. Kinahanglan nako og {amount} para sa piyansa. Ayaw isulti bisan kang kinsa.",
      "Mom, nawala ang wallet nako sa gawas. Palihug ipadala ang {amount} sa account nga kini.",
    ],
    questionTemplates: ["Murag eksaktong tingog sa anak nimo. Unsa ang buhaton nimo?"],
    optionTemplates: {
      correct: ["Tawagon ang TINUOD nga naka-save nga numero sa anak nako sa dili pa magpadala og bisan unsa."],
      wrong: ["Ipadala ang kwarta. Anak nako gyud kana.", "Pangutana og pangutana nga anak ra nako ang nakahibalo.", "Ipadala ang tunga karon."],
    },
    correctFeedback: ["Sakto. Nag-verify ka sa dili pa molihok. Ayaw pagsalig sa wala mailhing 'bag-ong numero'."],
    wrongFeedback: ["Ang 'ayaw pagtawag' nga hangyo ang red flag; gigamit kini sa scammer aron hunongon ka sa pag-verify."],
    archetypes: ["trap"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "remittance",
    rule: "Dili ka mobayad og fee aron makadawat og remittance.",
    brands: ["WesternUnion", "Palawan", "Remitly"],
    channels: ["sms", "chat", "email"],
    correctAction: "never_pay_to_receive",
    messageTemplates: ["Naka-hold ang remittance nimo nga {amount}. Bayari ang release fee sa {domain} aron madawat kini.",
      "Naghulat ang remittance nimo nga {amount}, pero kinahanglan mobayad ka og {amount} release fee una sa {domain}.",
      "Palawan: I-claim ang kwarta nimo. I-confirm sa {domain} aron ma-release ang {amount}."],
    questionTemplates: ["Naay mensahe nga nag-ingon kinahanglan og fee ang remittance nimo. Unsa ang buhaton nimo?"],
    optionTemplates: {
      correct: ["I-check ang remittance app nako o ang opisyal nga branch mismo."],
      wrong: ["Bayari ang release fee aron makuha nako ang kwarta.", "Mag-reply para mag-confirm.", "Mangayo og tabang sa kaibigan nga mobayad."],
    },
    correctFeedback: ["Sakto. Moabot ra ang tinuod nga transfer; walay kinahanglan mobayad aron makadawat og kwarta."],
    wrongFeedback: ["Ang pagbayad aron makadawat og kwarta mao ang advance-fee trick: mobayad ka, dili moabot ang kwarta."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "loan-app",
    rule: "Dili maningil og penalty ang tinuod nga lender pinaagi sa estranghero.",
    brands: ["LendFast", "CashKo"],
    channels: ["sms", "chat", "vishing"],
    correctAction: "report_to_authority",
    messageTemplates: ["Bayari ang overdue penalty nimo nga {amount} karon o kontakon namo ang tanang contacts nimo sa {domain}.",
      "Ang loan penalty nimo {amount}. Bayari karon sa {domain} o ma-notify ang contacts nimo.",
      "Final notice: bayari ang {amount} karon aron malikayan ang escalation."],
    questionTemplates: ["Naay lender nga naghulga nga kontakon ang tanan. Unsa ang buhaton nimo?"],
    optionTemplates: {
      correct: ["Ayaw pagbayad. I-report ang harassment sa DTI o CICC."],
      wrong: ["Bayari ang penalty aron mohunong sila.", "Ipadala ang {amount} aron mohulat sila.", "Mag-reply para mag-negotiate."],
    },
    correctFeedback: ["Sakto. Illegal ang loan-app harassment; i-report kini imbes nga mobayad sa estranghero."],
    wrongFeedback: ["Ang pagbayad sa estranghero dili mohunong sa mga hulga; i-report kini sa awtoridad."],
    archetypes: ["trap"],
    difficulties: ["medium", "hard"],
  },
  {
    family: "charity",
    rule: "Mag-donate lamang sa na-verify nga opisyal nga channel.",
    brands: ["ReliefFund", "ChurchAid"],
    channels: ["sms", "chat"],
    correctAction: "verified_channel_only",
    messageTemplates: ["Mag-donate sa mga biktima sa bagyo! Ipadala ang {amount} sa numero nga kini. Bawat piso makatabang.",
      "Tabangi ang typhoon drive namo! Bawat {amount} nagpakain og pamilya. Ipadala sa numero nga kini.",
      "Kinahanglan sa orphanage nga kini og {amount}. Mag-donate karon ug luwasa ang usa ka bata."],
    questionTemplates: ["Naay estranghero nga nangayo og donasyon. Unsa ang buhaton nimo?"],
    optionTemplates: {
      correct: ["I-check una kung tinuod ug na-verify ang charity."],
      wrong: ["Ipadala ang {amount} aron matabangan ang mga biktima.", "I-share ang numero aron makapag-donate ang uban."],
    },
    correctFeedback: ["Sakto. I-verify ang charity pinaagi sa opisyal nga channel sa dili pa mobuhat."],
    wrongFeedback: ["Gigamit sa scammer ang disaster aron mangolekta og 'donasyon' nga para nila, dili sa mga biktima."],
    archetypes: ["trap"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "fake-reward",
    rule: "Dili ka makadaog sa raffle nga wala nimo nasudlan.",
    brands: ["PCSO", "GCash", "MallVoucher"],
    channels: ["sms", "email", "chat"],
    correctAction: "ignore_and_report",
    messageTemplates: ["Congratulations! Nakadaog ka og {amount}! I-claim sa {domain} sa dili pa ma-expire.",
      "Nakadaog ka og {amount} sa anniversary draw namo! I-claim sa {domain} karon.",
      "Nakadaog ang GCash raffle ticket nimo! Mobayad og gamay nga fee sa {domain} aron madawat ang {amount}.",
      "Katapusang adlaw para i-claim ang premyo nimo nga {amount}! Bisitaha ang {domain}."],
    questionTemplates: ["Nakadaog ka sa raffle nga wala nimo nasudlan. Unsa ang buhaton nimo?"],
    optionTemplates: {
      correct: ["I-ignore kini. Wala ka nasudlan, busa peke kini."],
      wrong: ["I-click dayon ang link sa dili pa ma-expire ang premyo.", "I-forward sa kaibigan aron makadaog usab sila.", "Magpadala og gamay nga fee aron i-claim ang premyo."],
    },
    correctFeedback: ["Sakto. Kung wala ka nasudlan, dili ka makadaog. Kini ang klasiko nga fake-reward scam."],
    wrongFeedback: ["Dili mobayad ang mananaog aron i-claim ang premyo. Dili ka makadaog sa raffle nga wala nimo nasudlan."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "good-message",
    rule: "Naay tinuod nga OTP text. Ang scam mao ang bisan kinsa nga nangutana nimo nga IPADALA ang code.",
    brands: ["GCASH", "MAYA", "SHOPEE", "LAZADA"],
    channels: ["sms", "email"],
    correctAction: "recognize_legit",
    messageTemplates: [
      "{sender}: Ang verification code nimo kay 4126. Ayaw ipaambit kini nga code kang bisan kinsa. Dili kini pangayoon sa {sender}.",
      "{sender}: Na-ship na ang order nimo. I-track sa app.",
      "{sender}: Salamat sa cash-in nimo nga {amount}. Available na ang bag-ong balance nimo sa app.",
    ],
    questionTemplates: ["Murag tinuod nga mensahe kini. Scam ba?", "Naay mensahe gikan sa kompanya nga gigamit nimo. Unsa ang buhaton nimo?"],
    optionTemplates: {
      correct: ["Tinuod kini. Gikan sa opisyal nga sender ug dili mangayo og ipadala."],
      wrong: ["Scam kini kay gibanggit ang code.", "I-block ug i-report.", "Mag-reply para i-confirm ang identity nako."],
    },
    correctFeedback: ["Sakto. Giingnan ka sa tinuod nga OTP text nga itago kini; ang scam mao ang bisan kinsa nga NANGUTANA nimo nga ipadala."],
    wrongFeedback: ["Ang pag-flag sa bawat tinuod nga mensahe makapawala sa pagsalig nimo. Ang test kung naay NANGUTANA nimo nga molihok."],
    archetypes: ["good-message"],
    difficulties: ["medium", "hard"],
  },
];
