// === DOJO LOCALIZED TEMPLATES: ILOCANO ===
// Slot placeholders preserved verbatim; brands/channels/archetypes/actions/difficulties not translated.

import { TemplateFamily } from "./dojo-templates";

export const POOLS_ILOCANO = {
  amounts: ["P150", "P250", "P500", "P1,500", "P2,000", "P5,000", "P8,000", "P12,000", "P25,000", "P45,000", "P100,000", "P1,000,000"],
  fakeDomains: [
    "g-cash-verify-ph.top",
    "bdo-secure-login-verify.top",
    "jnt-tracking-ph.site",
    "maya-security-alert.xyz",
    "pagibig-loan-release.site",
    "bit.ly/verify-now",
    "gcash-update.ph-verify.top",
    "smart-rewar-ds.top",
    "shopee-refund-ph.site",
    "gov-ph-tax.site",
  ],
  urgencyTriggers: [
    "na-lock ti account mo",
    "mapukaw ti kuarta mo iti 24 nga oras",
    "daytoyen ti maudi a gundaway mo",
    "adda case number a na-file kontra kenka",
    "maisublin ti parcel mo",
    "maikansela ti benefits mo",
    "adda nakita nga unauthorized transfer",
    "ma-deactivate ti SIM mo",
  ],
  victimProfiles: [
    "Lola iti probinsya",
    "estudyante iti Manila",
    "OFW iti Riyadh",
    "tagikuada ti sari-sari store",
    "driver ti jeepney",
    "call-center agent",
    "senior pensioner",
    "bassit nga online seller",
  ],
  senderLabels: {
    GCASH: "GCash", MAYA: "Maya", GOTYME: "GoTyme", SHOPEEPAY: "ShopeePay",
    BDO: "BDO Alerts", BPI: "BPI", METROBANK: "Metrobank", UNIONBANK: "UnionBank",
    RCBC: "RCBC", LANDBANK: "LandBank", PNB: "PNB", SECURITY_BANK: "Security Bank",
    GLOBE: "Globe", SMART: "Smart", DITO: "DITO", PLDT: "PLDT Home",
    JNT: "J&T Express", LBC: "LBC", NINJAVAN: "Ninja Van", FLASH: "Flash Express",
    SHOPEE: "Shopee", LAZADA: "Lazada", BIR: "BIR", SSS: "SSS", PAGIBIG: "Pag-IBIG",
    PHILHEALTH: "PhilHealth", NBI: "NBI", PNP: "PNP-ACG", CICC: "CICC",
  },
};

export const TEMPLATE_FAMILIES_ILOCANO: TemplateFamily[] = [
  {
    family: "ewallet",
    rule: "Sekreto ti OTP. DIDA nga agdawat iti OTP ti pudno a kompanya.",
    brands: ["GCASH", "MAYA", "GOTYME", "SHOPEEPAY"],
    channels: ["sms", "email", "chat", "vishing"],
    correctAction: "verify_in_official_app",
    messageTemplates: [
      "{sender}: {urg} I-reply ti OTP mo itan tapos ma-reactivate, wenno mapukaw ti kuarta mo iti 24 nga oras.",
      "{sender} Alerto: {urg}. I-verify iti {domain} wenno ma-suspend ti account mo.",
      "{sender}: Addan nga umay a transfer nga {amount}! Agbayad nga umuna ti bassit a release fee tapos maawat daytoy.",
      "{sender}: Nakita mi ti suspicious login iti account mo. I-verify itan iti {domain} wenno ma-lock daytoy.",
      "{sender}: Ma-expire ti MPIN mo itan. I-update daytoy iti {domain} tapos magusar pay ti wallet mo.",
      "{sender}: Error iti double refund! Tapos ma-correct, kumpirmaam ti account mo iti {domain} iti 24 nga oras.",
    ],
    questionTemplates: ["Adda mensahe nga agsasao {urg} ken agdawdawat iti OTP. Ania ti aramidem?", "Adda text nga agsasao nga masapul nga agtignay ka a dagus. Ania ti aramidem?"],
    optionTemplates: {
      correct: ["Lukatan ti pudno nga {brand} app ken i-check ti account ko."],
      wrong: ["I-reply ti OTP a dagus tapos natalged ti kuarta ko.", "Awagan ti numero iti text tapos ma-verify.", "Bayadan ti release fee tapos maawat ti transfer."],
    },
    correctFeedback: ["Usto. In-check mo ti pudno nga {brand} app imbes a mamati iti text. Ti account mo ti source of truth, saan ti mensahe."],
    wrongFeedback: [
      "Saan nga agdawdawat iti OTP ti pudno a {brand}. Ti mensahe nga dayta ti scam.",
      "Ti numero nga dayta para iti scammer. Usaren laeng ti opisial nga {official}.",
      "No agbayad ka tapos makaawat ti kuarta, scam dayta.",
    ],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "bank",
    rule: "Awan pudno a bangko nga agdawdawat iti OTP wenno card code mo.",
    brands: ["BDO", "BPI", "METROBANK", "UNIONBANK", "RCBC", "LANDBANK", "PNB", "SECURITY_BANK"],
    channels: ["email", "sms", "vishing"],
    correctAction: "call_official_hotline",
    messageTemplates: [
      "{sender}: {urg}. I-click ti {domain} tapos i-verify ti identity mo itan.",
      "{sender} Fraud Dept: nakakita ti unauthorized transfer nga {amount}. I-reply ti card details mo tapos ma-reverse.",
      "{sender}: Naka-hold ti account mo para iti review. I-kumpirma ti identity mo iti {domain} tapos masublian ti access.",
      "{sender} Security: Adda baro a device a nag-try nga ag-login. I-approve wenno i-decline iti {domain}.",
      "{sender}: Masaradan ti card mo gapu iti inactivity. I-reactivate iti {domain}.",
    ],
    questionTemplates: ["Adda email nga agsasao nga adda iti peggad ti account mo. Ania ti aramidem?", "Kuna ti agtawtawag nga nagusar ti card mo iti fraud. Ania ti aramidem?"],
    optionTemplates: {
      correct: ["Ibabain ti tawag, kalpasanna awagan ti numero iti likud ti card ko.", "Lukatan ti bank app ko ken i-check no adda pudno nga alert."],
      wrong: ["Basaen ti card number ken 3-digit code ko tapos mapasardeng ti fraud.", "I-click ti link ken iserrek ti login ko tapos saan a maiserra ti account.", "Basaen iti likud ti code nga impatulod da."],
    },
    correctFeedback: ["Usto. Mabalin a peke ti caller ID ken sender name. Kanayon nga awagan ti pudno nga {official} number mismo."],
    wrongFeedback: ["Saan nga mangted iti card details wenno code iti phone wenno text link. Ammoen ti pudno a bangko ti card number mo."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "telco",
    rule: "Saan nga agdawdawat ti telco iti OTP wenno ID mo iti text.",
    brands: ["GLOBE", "SMART", "DITO", "PLDT"],
    channels: ["sms", "chat"],
    correctAction: "verify_in_official_app",
    messageTemplates: [
      "{sender}: Ma-expire dan ti points mo! I-redeem ti {amount} itan iti {domain}.",
      "{sender}: {urg} I-reply ti registered name ken address mo tapos agpabilin ti line mo.",
      "{sender}: Ngamin nga ma-expire ti account mo. I-renew iti {domain} tapos mapabilin ti number mo.",
      "{sender}: Nawaya nga {amount} load para kenka! I-claim iti {domain} itan.",
      "{sender}: Overdue ti bill mo. Bayadan ti {amount} iti {domain} tapos malikawan ti disconnection.",
    ],
    questionTemplates: ["Adda mensahe nga mangitangtango iti points wenno mangbaballaag iti line mo. Ania ti aramidem?"],
    optionTemplates: {
      correct: ["Lukatan ti opisial nga {brand} app ken i-check idiay."],
      wrong: ["I-click ti link ken iserrek ti details ko tapos ma-redeem.", "I-reply ti sibubukel a nagan ken adres ko.", "Awagan ti numero iti text."],
    },
    correctFeedback: ["Usto. I-check ti opisial nga {brand} app; saan nga agtalek iti text link."],
    wrongFeedback: ["Ti panag-reply wenno panag-click ket ibaga na iti scammer nga aktibo ti numero ken details mo."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "delivery",
    rule: "Bayadan ti delivery fee iti pudno nga app wenno iti ridaw, saan iti text link.",
    brands: ["JNT", "LBC", "NINJAVAN", "FLASH"],
    channels: ["sms", "chat"],
    correctAction: "compare_tracking",
    messageTemplates: [
      "{sender}: Naka-hold ti parcel mo para iti unpaid fee nga {amount}. Bayadan iti {domain} wenno maisublin ti package mo.",
      "{sender}: {urg} Tapos ma-reschedule ti delivery, agbayad ti bassit a fee iti {domain}.",
      "{sender}: Na-attempt ti delivery ngem napasakup. I-reschedule iti {domain} para iti {amount}.",
      "{sender}: Kasapulan ti package mo ti bassit a storage fee nga {amount}. Bayadan iti {domain}.",
      "{sender}: Saan a kompleto ti adres mo. I-confirm iti {domain} wenno maisublin ti parcel.",
    ],
    questionTemplates: ["Adda mensahe nga agsasao nga naka-hold ti parcel mo. Ania ti aramidem?"],
    optionTemplates: {
      correct: ["I-check nga umuna ti pudno a tracking number iti order app ko."],
      wrong: ["Bayadan ti fee tapos saan a maisublin ti parcel ko.", "Agbayad iti link tapos natalged.", "Ag-reply tapos ma-confirm."],
    },
    correctFeedback: ["Usto. Inkompara mo iti pudno a tracking ti order mo. No saan nga agtutop, peke dayta."],
    wrongFeedback: ["Ikolekta ti pudno a courier ti fee iti ridaw wenno iti opisial nga app da, saan iti random text link."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "customs",
    rule: "Saan nga mangarkensa iti fee ti customs iti text.",
    brands: ["LBC", "PHILPOST"],
    channels: ["sms", "email"],
    correctAction: "call_official_hotline",
    messageTemplates: [
      "{sender}: Naka-hold iti customs ti package mo. Bayadan ti {amount} clearance fee iti {domain} tapos ma-release.",
      "{sender} Customs: Naka-pending iti inspection ti international parcel mo. Bayadan ti {amount} inspection fee iti {domain}.",
      "{sender}: Nakakita ti customs iti undeclared items. I-clear iti {domain} para iti {amount}.",
    ],
    questionTemplates: ["Adda customs a kayatna ti clearance fee. Ania ti aramidem?"],
    optionTemplates: {
      correct: ["Awagan ti opisial nga hotline ti {sender} tapos ma-check no pudno."],
      wrong: ["Bayadan ti fee tapos ma-release ti customs ti package ko.", "Ag-reply tapos ma-confirm."],
    },
    correctFeedback: ["Usto. Nag-verify ka iti opisial nga channel. Peke ti text nga customs scam."],
    wrongFeedback: ["Saan nga mangarkensa iti fee ti customs iti text, ken no awan ti impatulod mo iti ruar, awan ti ma-clear."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "job",
    rule: "Ti trabaho a mangbayad KA tapos agtrabaho saan a trabaho, scam dayta.",
    brands: ["CryptoGlobal", "RemoteHire", "DataEntryPH"],
    channels: ["linkedin", "chat", "email"],
    correctAction: "never_pay_to_work",
    messageTemplates: [
      "Kayat mi ti profile mo! {amount}/bulan, work from home. I-download daytoy nga app tapos rugi ti training itan.",
      "Umuna a task mo: i-transfer ti {amount} kas refundable performance deposit.",
      "Congratulations! Nakapasar ka iti screening mi. Bayadan ti {amount} processing fee iti {domain} tapos rugi.",
      "HR ditoy: ngamin a malpas ti onboarding mo. Kumpirmaam iti {domain} para iti {amount} refundable deposit.",
      "Adda ka iti shortlist! I-confirm ti slot mo iti {domain} iti 24 nga oras.",
    ],
    questionTemplates: ["Adda tagtagainep a trabaho a naguna a nakakita kenka. Ania ti aramidem?", "Kayat da iti deposit tapos rugi ti trabaho. Ania ti aramidem?"],
    optionTemplates: {
      correct: ["I-search ti nagan ti kompanya ken i-check ti pudno a website da.", "Saan. Awan pudno a trabaho nga agdawdawat iti bayad tapos agtrabaho."],
      wrong: ["I-download a dagus ti app sakbay pay a pumili da iti sabali.", "Ipatulod ti deposit. Kuna da a refundable.", "Ipatulod ti kagudua ken mangted iti proof."],
    },
    correctFeedback: ["Usto. Adda verifiable web presence ti pudno a kompanya; saan da a dumardaras nga mang-install iti app wenno agbayad iti deposit."],
    wrongFeedback: ["Bayadan KA ti pudno nga employer. Saan da nga agdawdawat iti bayad tapos agrugika."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "romance",
    rule: "Saan nga agipatulod ti kuarta iti tao a saan mo pay nakita a personal.",
    brands: ["DatingApp"],
    channels: ["chat", "vishing"],
    correctAction: "never_send_to_stranger",
    messageTemplates: [
      "Ay-ayaten ka ngem na-stuck ak iti customs ken kasapulan ko ti {amount} tapos makakita ka. Mabalin nga ipatulod?",
      "Kasapulan ti crypto investment ko iti {amount} pay tapos ma-withdraw, kalpasanna bayadan ka.",
      "Adda problemak iti airport. Kasapulan da iti {amount} tapos ma-release ti visa ko. Ipatulod itan.",
      "Nag-invest ak para kadatayo, ngem kasapulan ko iti {amount} pay tapos ma-withdraw ken umay kenka.",
      "Na-freeze ti account ko. Mabalin nga i-hold ti {amount} para kaniak agingga ti isasangpet ko?",
    ],
    questionTemplates: ["Adda tao a nakilam iti online nga mangkasapulan iti kuarta itan. Ania ti aramidem?"],
    optionTemplates: {
      correct: ["Saan. Saan ko pay nakita daytoy a tao a personal."],
      wrong: ["Ipatulod ti kuarta tapos saan da nga ma-stuck.", "Mangted nga umuna iti proof, kalpasanna ipatulod.", "Ipatulod ti kagudua itan."],
    },
    correctFeedback: ["Usto. Ti romance scammer mangbangon iti talek tapos agdawdawat iti kuarta. Saan nga agipatulod iti kuarta iti saan mo pay nakita."],
    wrongFeedback: ["Naimbag ti panangted iti proof, ngem ti laeng natalged a sungbat ket saan nga agipatulod iti kuarta iti estranghero."],
    archetypes: ["trap", "redirect"],
    difficulties: ["medium", "hard"],
  },
  {
    family: "investment",
    rule: "Ti 'sure profit' a saan mo kiniddaw kanayon a scam.",
    brands: ["Binance", "SureKita", "CryptoPips"],
    channels: ["chat", "email", "sms"],
    correctAction: "ignore_and_report",
    messageTemplates: [
      "Garantisado a kita! Ag-invest iti {amount} itan, madoble iti maysa a lawas. Sure kita, pasok na!",
      "Dinoble ti AI trading app mi ti {amount} iti maysa a bulan. Rugi itan.",
      "Dinoble ti app mi ti {amount} iti 7 nga aldaw. Rugi ti account mo itan iti {domain}.",
      "Signal group: garantisado a {amount} payout iti lawas. Sumrek sakbay a maiserra.",
      "Ag-urnong iti {amount} inaldaw nga awan risk. Mag-withdraw anytime. Ag-invest itan.",
    ],
    questionTemplates: ["Adda tao a mangari ti garantisado a kita. Ania ti aramidem?"],
    optionTemplates: {
      correct: ["I-ignore ken i-report. Awan garantisado a kita."],
      wrong: ["Ag-invest iti {amount} tapos suboken.", "Rugi iti bassit tapos i-test.", "I-share iti pamilya tapos ag-urnong da met."],
    },
    correctFeedback: ["Usto. Ti 'garantisado a kita' ti kasalsalimetmetan a scam signal nga adda."],
    wrongFeedback: ["Ti siasinoman a mangari iti garantisado a kita ket alaenna ti kuarta mo, saan nga i-invest."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "government",
    rule: "Awan opisina ti gobyerno nga agdawdawat iti fee wenno OTP iti text.",
    brands: ["BIR", "SSS", "PAGIBIG", "PHILHEALTH", "NBI", "PNP", "CICC"],
    channels: ["sms", "email", "vishing"],
    correctAction: "call_official_hotline",
    messageTemplates: [
      "{sender}: {urg} Bayadan ti penalty mo nga {amount} iti {domain} tapos malikawan ti case filing.",
      "{sender}: Maikansela ti benefits mo malaksid no mag-verify ka iti {domain}.",
      "{sender}: Saganad ti tax refund mo nga {amount}. I-claim iti {domain} sakbay a ma-expire.",
      "{sender}: I-update ti records mo iti {domain} wenno ma-pause ti pension mo.",
      "{sender}: Adda warrant a na-issue kontra iti ID mo. I-resolve iti {domain} tapos malikawan ti panag-aresto.",
    ],
    questionTemplates: ["Adda opisina ti gobyerno nga mangbaballaag iti penalty iti text. Ania ti aramidem?"],
    optionTemplates: {
      correct: ["Awagan ti opisial nga hotline ti {sender} tapos ma-verify."],
      wrong: ["Bayadan ti penalty tapos malikawan ti kaso.", "I-click ti link ken iserrek ti details ko.", "Awagan ti numero iti text."],
    },
    correctFeedback: ["Usto. Saan nga mangarkensa iti fee ti gobyerno iti text; awagan ti opisial nga numero."],
    wrongFeedback: ["Adda opisial nga channel dagiti ahensya a kas iti {sender}. Impersonation ti text."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "quishing",
    rule: "Na-suspetsa ti QR code a saan mo kiniddaw.",
    brands: ["ParkingPH", "MerchantQR"],
    channels: ["qr"],
    correctAction: "use_official_payment",
    messageTemplates: ["[QR] I-scan tapos bayadan ti {amount} parking fee. Instant ken secure ti payment.",
      "[QR] I-scan tapos bayadan ti electric bill mo. Official partner. {amount} ti bayad.",
      "[QR] Bayadan ditoy ti food delivery mo. Paspas ken secure.",
      "[QR] I-verify ti parking exit mo babaen ti panag-scan daytoy a code."],
    questionTemplates: ["Adda QR code a mangitangtango nga agbayad iti parking. Ania ti aramidem?"],
    optionTemplates: {
      correct: ["Biruken ti opisial nga parking sign wenno agbayad iti machine."],
      wrong: ["I-scan ken agbayad. {amount} laeng dayta.", "I-scan ngem i-check ti page sakbay nga agbayad."],
    },
    correctFeedback: ["Usto. Kanayon nga usaren ti opisial a pamay-an ti panagbayad, saan ti sticker a kalit a nagparang."],
    wrongFeedback: ["Mabalin nga itudtudo ti QR nga dayta iti peke a payment page a mangtakaw iti card mo."],
    archetypes: ["trap"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "vishing",
    rule: "Mabalin a peke ti Caller ID. Ibabain ti tawag ken awagan ti opisial a numero.",
    brands: ["BDO", "BPI", "GLOBE", "SMART", "CICC"],
    channels: ["vishing"],
    correctAction: "hang_up_call_official",
    messageTemplates: [
      "Daytoy ti {sender} fraud department. Nagusar ti card mo para iti {amount}. Ibaga ti card number ken ti code iti likud.",
      "Kasapulan tayo nga i-secure ti account mo ITAN. Agipatulod ak iti code. Pangngaasi nga basuen iti likud.",
      "Daytoy ti {sender} tech support. Na-hack ti line mo. Ited ti code iti phone mo.",
      "Agtawtawag ak manipud iti {sender}. Adda tao a nag-try nga ag-access iti account mo. I-confirm ti details mo.",
      "{sender} agent ditoy. Tapos ma-reverse ti fraudulent transfer, kasapulan ko ti OTP mo.",
    ],
    questionTemplates: ["Ipakita ti caller ID ti pudno a bangko mo. Ania ti aramidem?"],
    optionTemplates: {
      correct: ["Ibabain ti tawag, kalpasanna awagan ti numero iti likud ti card ko."],
      wrong: ["Basaen ti card number ko tapos mapasardeng ti fraud.", "Basaen iti likud ti code nga impatulod da.", "Mangted nga umuna iti proof no siak da."],
    },
    correctFeedback: ["Usto. Mabalin a peke ti caller ID. Ibabain ti tawag ken awagan ti pudno a numero."],
    wrongFeedback: ["Saan nga agbasa iti code wenno card details iti tao a nagtawag kenka, uray kasano ka-opisial ti langada."],
    archetypes: ["trap", "redirect"],
    difficulties: ["medium", "hard"],
  },
  {
    family: "sim-pretext",
    rule: "Ag-register iti SIM iti opisial laeng a telco channel.",
    brands: ["GLOBE", "SMART", "DITO"],
    channels: ["sms", "chat", "vishing"],
    correctAction: "official_channel_only",
    messageTemplates: ["{sender}: {urg} Ag-re-register iti {domain} wenno mapukaw ti SIM mo.",
      "{sender}: Saan a fully registered ti SIM mo. Kompletoen iti {domain} wenno maputol ti line mo.",
      "{sender}: Kasapulan ti baro a SIM rules nga mag-verify ka iti {domain} iti 48 nga oras."],
    questionTemplates: ["Adda mensahe nga agsasao nga ma-deactivate ti SIM mo. Ania ti aramidem?"],
    optionTemplates: {
      correct: ["Lukatan ti opisial nga website wenno app ti {sender} ken i-check idiay."],
      wrong: ["I-click ti link ken iserrek ti ID ko.", "Awagan ti numero iti text."],
    },
    correctFeedback: ["Usto. Ti SIM registration ket mapasamak laeng iti opisial nga telco channel."],
    wrongFeedback: ["Ikolekta ti link nga dayta ti ID mo. Saan ka a i-text ti pudno a telco tapos ag-register iti random link."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "family-emergency",
    rule: "Usaren ti scammer dagiti nagan ti pamilya tapos mapabuteng ka. Awagan ti pudno a naka-save a numero.",
    brands: ["Child", "Relative"],
    channels: ["sms", "chat", "vishing"],
    correctAction: "call_real_number",
    messageTemplates: [
      "Mom/Dad, siak daytoy. Naburak ti phone ko. Ipatulod ti {amount} iti GCash nga daytoy. Pangngaasi saan nga agtawag, naburak ti phone ko.",
      "Siak daytoy, ti anak mo. Adda ak iti ospital. Kasapulan ti ospital iti {amount}. Pangngaasi ipatulod iti numero nga daytoy.",
      "Lola, adda problemak iti polis. Kasapulan ko iti {amount} para iti piyansa. Saan nga ibaga iti siasinoman.",
      "Mom, napukaw ti wallet ko iti ruar. Pangngaasi ipatulod ti {amount} iti account nga daytoy.",
    ],
    questionTemplates: ["Kasla eksakto ti timek ti anak mo. Ania ti aramidem?"],
    optionTemplates: {
      correct: ["Awagan ti PUDNO a naka-save a numero ti anak ko sakbay nga agipatulod iti aniaman."],
      wrong: ["Ipatulod ti kuarta. Anak ko dayta.", "Mangted iti saludsod nga anak ko laeng ti makaammo.", "Ipatulod ti kagudua itan."],
    },
    correctFeedback: ["Usto. Nag-verify ka sakbay nga nagtignay. Saan nga agtalek iti di-amammo a 'baro a numero'."],
    wrongFeedback: ["Ti 'saan nga agtawag' a kiddaw ti red flag; usaren dayta ti scammer tapos mapasardeng ka nga ag-verify."],
    archetypes: ["trap"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "remittance",
    rule: "Saan ka nga agbayad iti fee tapos makaawat ti remittance.",
    brands: ["WesternUnion", "Palawan", "Remitly"],
    channels: ["sms", "chat", "email"],
    correctAction: "never_pay_to_receive",
    messageTemplates: ["Naka-hold ti remittance mo nga {amount}. Bayadan ti release fee iti {domain} tapos maawat daytoy.",
      "Aguray ti remittance mo nga {amount}, ngem masapul nga agbayad ka iti {amount} release fee nga umuna iti {domain}.",
      "Palawan: I-claim ti kuarta mo. I-confirm iti {domain} tapos ma-release ti {amount}."],
    questionTemplates: ["Adda mensahe nga agsasao a kasapulan iti fee ti remittance mo. Ania ti aramidem?"],
    optionTemplates: {
      correct: ["I-check ti remittance app ko wenno ti opisial a branch mismo."],
      wrong: ["Bayadan ti release fee tapos maala ko ti kuarta.", "Ag-reply tapos ma-confirm.", "Mangted iti tulong ti gayyem nga agbayad."],
    },
    correctFeedback: ["Usto. Umay a mismo ti pudno a transfer; awan ti kasapulan nga agbayad tapos makaawat ti kuarta."],
    wrongFeedback: ["Ti panagbayad tapos makaawat ti kuarta ket ti advance-fee trick: agbayad ka, saan nga umay ti kuarta."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "loan-app",
    rule: "Saan nga mangarkensa iti penalty ti pudno a lender babaen iti estranghero.",
    brands: ["LendFast", "CashKo"],
    channels: ["sms", "chat", "vishing"],
    correctAction: "report_to_authority",
    messageTemplates: ["Bayadan ti overdue penalty mo nga {amount} itan wenno kontaken mi amin a contacts mo iti {domain}.",
      "Ti loan penalty mo ket {amount}. Bayadan itan iti {domain} wenno ma-notify ti contacts mo.",
      "Final notice: bayadan ti {amount} itan tapos malikawan ti escalation."],
    questionTemplates: ["Adda lender a mangbaballaag a kontaken ti amin. Ania ti aramidem?"],
    optionTemplates: {
      correct: ["Saan nga agbayad. I-report ti harassment iti DTI wenno CICC."],
      wrong: ["Bayadan ti penalty tapos mapasardeng da.", "Ipatulod ti {amount} tapos aguray da.", "Ag-reply tapos ma-negotiate."],
    },
    correctFeedback: ["Usto. Illegal ti loan-app harassment; i-report daytoy imbes nga agbayad iti estranghero."],
    wrongFeedback: ["Ti panagbayad iti estranghero saan a mapasardeng dagiti am-among; i-report daytoy iti autoridad."],
    archetypes: ["trap"],
    difficulties: ["medium", "hard"],
  },
  {
    family: "charity",
    rule: "Ag-donate laeng iti na-verify nga opisial a channel.",
    brands: ["ReliefFund", "ChurchAid"],
    channels: ["sms", "chat"],
    correctAction: "verified_channel_only",
    messageTemplates: ["Ag-donate kadagiti biktima ti bagyo! Ipatulod ti {amount} iti numero nga daytoy. Tunggal pisos ket tumulong.",
      "Tulongan ti typhoon drive mi! Tunggal {amount} ket mangpakan iti pamilya. Ipatulod iti numero nga daytoy.",
      "Kasapulan ti orphanage nga daytoy iti {amount}. Ag-donate itan ken isalakan ti maysa nga ubing."],
    questionTemplates: ["Adda estranghero nga agdawdawat iti donasyon. Ania ti aramidem?"],
    optionTemplates: {
      correct: ["I-check nga umuna no pudno ken na-verify ti charity."],
      wrong: ["Ipatulod ti {amount} tapos matulongan dagiti biktima.", "I-share ti numero tapos makapag-donate ti dadduma."],
    },
    correctFeedback: ["Usto. I-verify ti charity babaen iti opisial a channel sakbay nga mangted."],
    wrongFeedback: ["Usaren ti scammer ti disaster tapos mangala iti 'donasyon' nga para kadakuada, saan kadagiti biktima."],
    archetypes: ["trap"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "fake-reward",
    rule: "Saan ka a makapag-abak iti raffle a saan mo a sinrek.",
    brands: ["PCSO", "GCash", "MallVoucher"],
    channels: ["sms", "email", "chat"],
    correctAction: "ignore_and_report",
    messageTemplates: ["Congratulations! Nag-abak ka iti {amount}! I-claim iti {domain} sakbay a ma-expire.",
      "Nag-abak ka iti {amount} iti anniversary draw mi! I-claim iti {domain} itan.",
      "Nag-abak ti GCash raffle ticket mo! Agbayad ti bassit a fee iti {domain} tapos maawat ti {amount}.",
      "Maudi nga aldaw tapos i-claim ti premyo mo nga {amount}! Bisitaen ti {domain}."],
    questionTemplates: ["Nag-abak ka iti raffle a saan mo a sinrek. Ania ti aramidem?"],
    optionTemplates: {
      correct: ["I-ignore daytoy. Saan ka a simrek, isu a peke daytoy."],
      wrong: ["I-click a dagus ti link sakbay a ma-expire ti premyo.", "I-forward iti gayyem tapos makapag-abak da met.", "Agipatulod ti bassit a fee tapos i-claim ti premyo."],
    },
    correctFeedback: ["Usto. No saan ka a simrek, saan ka a makapag-abak. Daytoy ti klasiko a fake-reward scam."],
    wrongFeedback: ["Saan nga agbayad ti mannag-abak tapos i-claim ti premyo. Saan ka a makapag-abak iti raffle a saan mo a sinrek."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "good-message",
    rule: "Adda pudno nga OTP text. Ti scam ket ti siasinoman a mangdawdawat kenka nga IPATULOD ti code.",
    brands: ["GCASH", "MAYA", "SHOPEE", "LAZADA"],
    channels: ["sms", "email"],
    correctAction: "recognize_legit",
    messageTemplates: [
      "{sender}: Ti verification code mo ket 4126. Saan nga ibingay daytoy a code iti siasinoman. Saan daytoy a dawaten ti {sender}.",
      "{sender}: Na-ship ti order mo. I-track iti app.",
      "{sender}: Agyaman iti cash-in mo nga {amount}. Available ti baro a balance mo iti app.",
    ],
    questionTemplates: ["Kasla pudno a mensahe daytoy. Scam kadi?", "Adda mensahe manipud iti kompanya nga us-usarem. Ania ti aramidem?"],
    optionTemplates: {
      correct: ["Pudno daytoy. Manipud iti opisial nga sender ken saan nga agdawdawat nga agipatulod."],
      wrong: ["Scam daytoy ta nangibaga iti code.", "I-block ken i-report.", "Ag-reply tapos i-confirm ti identity ko."],
    },
    correctFeedback: ["Usto. Ibaga ti pudno nga OTP text nga isekreto daytoy; ti scam ket ti siasinoman a MANGDAWDAWAT kenka nga ipatulod."],
    wrongFeedback: ["Ti panang-flag iti tunggal pudno a mensahe ket mangaramid nga saan ka agtalek iti aniaman. Ti test no adda MANGDAWDAWAT kenka nga agtignay."],
    archetypes: ["good-message"],
    difficulties: ["medium", "hard"],
  },
];
