// === DOJO TEMPLATE FAMILIES ===
// The authoring layer for the 500-scenario library. Each family defines the
// rule it teaches, the brands/channels it can wear, message/option/feedback
// skeletons with {slots}, and which archetypes/difficulties it supports.
// The generator (generator.ts) fills the slots deterministically.

import {
  ScenarioChannel,
  ScenarioFamily,
  ScenarioArchetype,
  ScenarioDifficulty,
} from "./scenarios";

export interface TemplateFamily {
  family: ScenarioFamily;
  rule: string; // the one memorable Taglish/English rule, reused as tip base
  brands: string[];
  channels: ScenarioChannel[];
  correctAction: string; // machine key: verify_in_official_app | call_official_hotline | ignore_and_report | never_pay_to_receive | etc
  messageTemplates: string[]; // sentence skeletons with {brand} {amount} {urg} {domain} {sender}
  questionTemplates: string[];
  optionTemplates: { correct: string[]; wrong: string[] }; // with {action}
  correctFeedback: string[]; // with {brand} {official}
  wrongFeedback: string[]; // with {trap}
  archetypes: ScenarioArchetype[];
  difficulties: ScenarioDifficulty[];
}

// Curated slot value pools (seeded-sampled by the generator).
export const POOLS = {
  amounts: ["P150", "P250", "P500", "P1,500", "P2,000", "P5,000", "P8,000", "P12,000", "P25,000", "P45,000", "P100,000", "P1,000,000"],
  fakeDomains: [
    "g-cash-verify-ph.top",
    "bdo-secure-login-verify.top",
    "jnt-tracking-ph.site",
    "maya-security-alert.xyz",
    "pagibig-loan-release.site",
    "bit.ly/verify-now",
    "gcash-update.ph-verify.top",
    "smart-rewar-ds.top",
    "shopee-refund-ph.site",
    "gov-ph-tax.site",
  ],
  urgencyTriggers: [
    "your account is locked",
    "your money will be gone in 24 hours",
    "this is your last chance",
    "a case number has been filed against you",
    "your parcel will be returned",
    "your benefits will be cancelled",
    "an unauthorized transfer was detected",
    "your SIM will be deactivated",
  ],
  victimProfiles: [
    "Lola in the province",
    "college student in Manila",
    "OFW in Riyadh",
    "sari-sari store owner",
    "jeepney driver",
    "call-center agent",
    "senior pensioner",
    "small online seller",
  ],
  senderLabels: {
    GCASH: "GCash", MAYA: "Maya", GOTYME: "GoTyme", SHOPEEPAY: "ShopeePay",
    BDO: "BDO Alerts", BPI: "BPI", METROBANK: "Metrobank", UNIONBANK: "UnionBank",
    RCBC: "RCBC", LANDBANK: "LandBank", PNB: "PNB", SECURITY_BANK: "Security Bank",
    GLOBE: "Globe", SMART: "Smart", DITO: "DITO", PLDT: "PLDT Home",
    JNT: "J&T Express", LBC: "LBC", NINJAVAN: "Ninja Van", FLASH: "Flash Express",
    SHOPEE: "Shopee", LAZADA: "Lazada", BIR: "BIR", SSS: "SSS", PAGIBIG: "Pag-IBIG",
    PHILHEALTH: "PhilHealth", NBI: "NBI", PNP: "PNP-ACG", CICC: "CICC",
  },
};

export const TEMPLATE_FAMILIES: TemplateFamily[] = [
  {
    family: "ewallet",
    rule: "OTPs are secret. A real company NEVER asks you to send your OTP.",
    brands: ["GCASH", "MAYA", "GOTYME", "SHOPEEPAY"],
    channels: ["sms", "email", "chat", "vishing"],
    correctAction: "verify_in_official_app",
    messageTemplates: [
      "{sender}: {urg} Reply with your OTP now to reactivate, or your money will be gone in 24 hours.",
      "{sender} Alert: {urg}. Verify at {domain} or your account will be suspended.",
      "{sender}: You have an incoming transfer of {amount}! Pay a small release fee first to receive it.",
    "{sender}: We detected a suspicious login on your account. Verify now at {domain} or it will be locked.",
    "{sender}: Your MPIN will expire today. Update it at {domain} to keep using your wallet.",
    "{sender}: Double refund error! To correct it, confirm your account at {domain} within 24 hours."],
    questionTemplates: ["A message says {urg} and asks for your OTP. What do you do?", "A text says you must act now. What do you do?"],
    optionTemplates: {
      correct: ["Open the real {brand} app myself and check my account."],
      wrong: ["Reply with the OTP right away so my money is safe.", "Call the number in the text to verify.", "Pay the release fee so I can receive the transfer."],
    },
    correctFeedback: ["Correct. You checked the real {brand} app instead of trusting the text. Your account is the source of truth, not a message."],
    wrongFeedback: [
      "Real {brand} never asks for your OTP. That message is the scam.",
      "That number belongs to the scammer. Use the official {official} number only.",
      "If you pay to receive money, it is a scam.",
    ],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "bank",
    rule: "No real bank ever asks for your OTP or card code.",
    brands: ["BDO", "BPI", "METROBANK", "UNIONBANK", "RCBC", "LANDBANK", "PNB", "SECURITY_BANK"],
    channels: ["email", "sms", "vishing"],
    correctAction: "call_official_hotline",
    messageTemplates: [
      "{sender}: {urg}. Click {domain} to verify your identity now.",
      "{sender} Fraud Dept: an unauthorized transfer of {amount} was detected. Reply with your card details to reverse it.",
    "{sender}: Your account is on hold for review. Confirm your identity at {domain} to restore access.",
    "{sender} Security: A new device tried to log in. Approve or decline at {domain}.",
    "{sender}: Your card will be closed due to inactivity. Reactivate at {domain}."],
    questionTemplates: ["An email says your account is at risk. What do you do?", "The caller says your card was used for fraud. What do you do?"],
    optionTemplates: {
      correct: ["Hang up, then call the number on the back of my card.", "Open my bank app directly and check for any real alert."],
      wrong: ["Read my card number and the 3-digit code to stop the fraud.", "Click the link and enter my login so my account is not closed.", "Read back the code they sent me."],
    },
    correctFeedback: ["Correct. Caller ID and sender names can be faked. Always call the real {official} number yourself."],
    wrongFeedback: ["Never give card details or codes over the phone or a text link. Real banks already have your card number."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "telco",
    rule: "Telcos never ask for your OTP or personal ID by text.",
    brands: ["GLOBE", "SMART", "DITO", "PLDT"],
    channels: ["sms", "chat"],
    correctAction: "verify_in_official_app",
    messageTemplates: [
      "{sender}: Your points are expiring! Redeem {amount} worth now at {domain}.",
      "{sender}: {urg} Reply with your registered name and address to keep your line.",
    "{sender}: Your account is about to expire. Renew at {domain} to keep your number.",
    "{sender}: Free {amount} load for you! Claim at {domain} now.",
    "{sender}: Your bill is overdue. Pay {amount} at {domain} to avoid disconnection."],
    questionTemplates: ["A message offers points or warns about your line. What do you do?"],
    optionTemplates: {
      correct: ["Open the official {brand} app and check there."],
      wrong: ["Click the link and enter my details to redeem.", "Reply with my full name and address.", "Call the number in the text."],
    },
    correctFeedback: ["Correct. Check the official {brand} app; never trust a text link."],
    wrongFeedback: ["Replying or clicking tells scammers your number and details are live."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "delivery",
    rule: "Delivery fees are paid through the real app or at the door, never a text link.",
    brands: ["JNT", "LBC", "NINJAVAN", "FLASH"],
    channels: ["sms", "chat"],
    correctAction: "compare_tracking",
    messageTemplates: [
      "{sender}: Your parcel is on hold for an unpaid fee of {amount}. Pay at {domain} or your package will be returned.",
      "{sender}: {urg} To reschedule delivery, pay a small fee at {domain}.",
    "{sender}: Delivery attempted but failed. Reschedule at {domain} for {amount}.",
    "{sender}: Your package needs a small storage fee of {amount}. Pay at {domain}.",
    "{sender}: Your address is incomplete. Confirm at {domain} or the parcel returns."],
    questionTemplates: ["A message says your parcel is on hold. What do you do?"],
    optionTemplates: {
      correct: ["Check the real tracking number in my order app first."],
      wrong: ["Pay the fee so my parcel is not returned.", "Pay via the link to be safe.", "Reply to confirm."],
    },
    correctFeedback: ["Correct. You compared with the real tracking from your order. If it does not match, it is fake."],
    wrongFeedback: ["Real couriers collect fees at your door or in their official app, never through a random text link."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "customs",
    rule: "Customs never collects fees by text.",
    brands: ["LBC", "PHILPOST"],
    channels: ["sms", "email"],
    correctAction: "call_official_hotline",
    messageTemplates: [
      "{sender}: Your package is held by customs. Pay {amount} clearance fee at {domain} to release it.",
    "{sender} Customs: Your international parcel is pending inspection. Pay {amount} inspection fee at {domain}.",
    "{sender}: Customs found undeclared items. Clear them at {domain} for {amount}."],
    questionTemplates: ["Customs wants a clearance fee. What do you do?"],
    optionTemplates: {
      correct: ["Call the official {sender} hotline to check if this is real."],
      wrong: ["Pay the fee so customs releases my package.", "Reply to confirm."],
    },
    correctFeedback: ["Correct. You verified through the official channel. The text is a fake customs scam."],
    wrongFeedback: ["Customs does not collect fees by text, and if you never sent anything from abroad, there is nothing to clear."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "job",
    rule: "A job that makes YOU pay to work is not a job, it is a scam.",
    brands: ["CryptoGlobal", "RemoteHire", "DataEntryPH"],
    channels: ["linkedin", "chat", "email"],
    correctAction: "never_pay_to_work",
    messageTemplates: [
      "We love your profile! {amount}/month working from home. Download this app to start training today.",
      "Your first task: transfer {amount} as a refundable performance deposit.",
    "Congratulations! You passed our screening. Pay a {amount} processing fee at {domain} to start.",
    "HR here: your onboarding is almost done. Complete it at {domain} for {amount} refundable deposit.",
    "You are shortlisted! Confirm your slot at {domain} within 24 hours."],
    questionTemplates: ["A dream job found you first. What do you do?", "They want a deposit to start the job. What do you do?"],
    optionTemplates: {
      correct: ["Search the company name and check their real website first.", "Say no. No real job asks you to pay to work."],
      wrong: ["Download the app immediately before they pick someone else.", "Send the deposit. It says it is refundable.", "Send half and ask for proof."],
    },
    correctFeedback: ["Correct. A real company has a verifiable web presence; they never rush you to install apps or pay deposits."],
    wrongFeedback: ["Real employers pay YOU. They never ask you to pay to start working."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "romance",
    rule: "Never send money to someone you never met in person.",
    brands: ["DatingApp"],
    channels: ["chat", "vishing"],
    correctAction: "never_send_to_stranger",
    messageTemplates: [
      "I love you but I am stuck at customs and need {amount} to see you. Can you send it?",
      "My crypto investment needs {amount} more to withdraw, then I will pay you back.",
    "I am in trouble at the airport. They need {amount} to release my visa. Please send it now.",
    "I invested for us, but I need {amount} more to withdraw and come to you.",
    "My account is frozen. Can you hold {amount} for me until I arrive?"],
    questionTemplates: ["Someone you met online needs money urgently. What do you do?"],
    optionTemplates: {
      correct: ["Say no. I have never met this person in person."],
      wrong: ["Send the money so they are not stuck.", "Ask for proof first, then send.", "Send half now."],
    },
    correctFeedback: ["Correct. Romance scammers build trust to ask for money. Never send money to someone you never met."],
    wrongFeedback: ["Asking for proof is good, but the only safe answer is not to send money to a stranger."],
    archetypes: ["trap", "redirect"],
    difficulties: ["medium", "hard"],
  },
  {
    family: "investment",
    rule: "Unsolicited 'sure profit' is always a scam.",
    brands: ["Binance", "SureKita", "CryptoPips"],
    channels: ["chat", "email", "sms"],
    correctAction: "ignore_and_report",
    messageTemplates: [
      "Guaranteed profit! Invest {amount} today, earn double in a week. Sure kita, pasok na!",
      "Our AI trading app grew {amount} into {amount} in a month. Start now.",
    "Our app doubled {amount} in 7 days. Start your account today at {domain}.",
    "Signal group: guaranteed {amount} payout this week. Join before it closes.",
    "Earn {amount} daily with zero risk. Withdraw anytime. Invest now."],
    questionTemplates: ["Someone promises guaranteed profit. What do you do?"],
    optionTemplates: {
      correct: ["Ignore and report it. There is no guaranteed profit."],
      wrong: ["Invest {amount} to try it.", "Start small to test it.", "Share it with family so they can earn too."],
    },
    correctFeedback: ["Correct. 'Guaranteed profit' is the loudest scam signal there is."],
    wrongFeedback: ["Anyone promising guaranteed profit is taking your money, not investing it."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "government",
    rule: "No government office asks for fees or OTP by text.",
    brands: ["BIR", "SSS", "PAGIBIG", "PHILHEALTH", "NBI", "PNP", "CICC"],
    channels: ["sms", "email", "vishing"],
    correctAction: "call_official_hotline",
    messageTemplates: [
      "{sender}: {urg} Pay your penalty of {amount} at {domain} to avoid case filing.",
      "{sender}: Your benefits will be cancelled unless you verify at {domain}.",
    "{sender}: Your tax refund of {amount} is ready. Claim at {domain} before it expires.",
    "{sender}: Update your records at {domain} or your pension is paused.",
    "{sender}: A warrant was issued against your ID. Resolve at {domain} to avoid arrest."],
    questionTemplates: ["A government office threatens penalties by text. What do you do?"],
    optionTemplates: {
      correct: ["Call the official {sender} hotline to verify."],
      wrong: ["Pay the penalty so I avoid a case.", "Click the link and enter my details.", "Call the number in the text."],
    },
    correctFeedback: ["Correct. Government offices never collect fees by text; call the official number."],
    wrongFeedback: ["Agencies like {sender} have official channels. The text is impersonation."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "quishing",
    rule: "QR codes you did not ask for are suspicious.",
    brands: ["ParkingPH", "MerchantQR"],
    channels: ["qr"],
    correctAction: "use_official_payment",
    messageTemplates: ["[QR] Scan to pay {amount} parking fee. Payment is instant and secure.",
    "[QR] Scan to pay your electricity bill. Official partner. {amount} due.",
    "[QR] Pay for your food delivery here. Fast and secure.",
    "[QR] Verify your parking exit by scanning this code."],
    questionTemplates: ["A QR code offers to pay for parking. What do you do?"],
    optionTemplates: {
      correct: ["Look for the official parking sign or pay at the machine."],
      wrong: ["Scan it and pay. It is only {amount}.", "Scan it but check the page before paying."],
    },
    correctFeedback: ["Correct. Always use the official payment method, never a sticker that appeared out of nowhere."],
    wrongFeedback: ["That QR may point to a fake payment page that steals your card."],
    archetypes: ["trap"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "vishing",
    rule: "Caller ID can be fake. Hang up and call the official number yourself.",
    brands: ["BDO", "BPI", "GLOBE", "SMART", "CICC"],
    channels: ["vishing"],
    correctAction: "hang_up_call_official",
    messageTemplates: [
      "This is {sender} fraud department. Your card was used for {amount}. Say your card number and the code on the back.",
      "We need to secure your account NOW. I will send you a code. Please read it back.",
    "This is {sender} tech support. Your line was hacked. Give me the code on your phone.",
    "I am calling from {sender}. Someone tried to access your account. Confirm your details.",
    "{sender} agent here. To reverse a fraudulent transfer, I need your OTP."],
    questionTemplates: ["The caller ID shows your real bank. What do you do?"],
    optionTemplates: {
      correct: ["Hang up, then call the number on the back of my card."],
      wrong: ["Read my card number to stop the fraud.", "Read back the code they sent me.", "Ask them to prove who they are first."],
    },
    correctFeedback: ["Correct. Caller ID can be faked. Hang up and call the real number yourself."],
    wrongFeedback: ["Never read a code or card details to someone who called you, no matter how official they sound."],
    archetypes: ["trap", "redirect"],
    difficulties: ["medium", "hard"],
  },
  {
    family: "sim-pretext",
    rule: "Register your SIM only on official telco channels.",
    brands: ["GLOBE", "SMART", "DITO"],
    channels: ["sms", "chat", "vishing"],
    correctAction: "official_channel_only",
    messageTemplates: ["{sender}: {urg} Re-register at {domain} or lose your SIM.",
    "{sender}: Your SIM is not fully registered. Complete it at {domain} or your line is cut.",
    "{sender}: New SIM rules require you to verify at {domain} within 48 hours."],
    questionTemplates: ["A message says your SIM will be deactivated. What do you do?"],
    optionTemplates: {
      correct: ["Open the official {sender} website or app and check there."],
      wrong: ["Click the link and enter my ID.", "Call the number in the text."],
    },
    correctFeedback: ["Correct. SIM registration happens only on official telco channels."],
    wrongFeedback: ["That link harvests your ID. Real telcos never text you to re-register at a random link."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "family-emergency",
    rule: "Scammers use family names to panic you. Call the real saved number.",
    brands: ["Child", "Relative"],
    channels: ["sms", "chat", "vishing"],
    correctAction: "call_real_number",
    messageTemplates: [
      "Mom/Dad, it's me. I broke my phone. Send {amount} to this GCash. Please don't call, my phone is broken.",
    "It is me, your son. I am in the hospital. The hospital needs {amount}. Please send to this number.",
    "Grandma, I am in trouble with the police. I need {amount} for bail. Do not tell anyone.",
    "Mom, I lost my wallet abroad. Send {amount} to this account please."],
    questionTemplates: ["It sounds exactly like your child. What do you do?"],
    optionTemplates: {
      correct: ["Call the REAL saved number of my child before sending anything."],
      wrong: ["Send the money. It must be my child.", "Ask a question only my child would know.", "Send half now."],
    },
    correctFeedback: ["Correct. You verified before acting. Never trust an unknown 'new number'."],
    wrongFeedback: ["The 'don't call' request is the red flag; scammers use it to stop you verifying."],
    archetypes: ["trap"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "remittance",
    rule: "You never pay a fee to receive a remittance.",
    brands: ["WesternUnion", "Palawan", "Remitly"],
    channels: ["sms", "chat", "email"],
    correctAction: "never_pay_to_receive",
    messageTemplates: ["Your remittance of {amount} is on hold. Pay a release fee at {domain} to receive it.",
    "Your remittance of {amount} is waiting, but you must pay a {amount} release fee first at {domain}.",
    "Palawan: Claim your money. Confirm at {domain} to release {amount}."],
    questionTemplates: ["A message says your remittance needs a fee. What do you do?"],
    optionTemplates: {
      correct: ["Check my remittance app or the official branch directly."],
      wrong: ["Pay the release fee so I get my money.", "Reply to confirm.", "Ask a friend to pay it for me."],
    },
    correctFeedback: ["Correct. A real transfer arrives by itself; no one needs you to pay to receive money."],
    wrongFeedback: ["Paying to receive money is the advance-fee trick: you pay, the money never arrives."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "loan-app",
    rule: "Real lenders never collect penalties through a stranger.",
    brands: ["LendFast", "CashKo"],
    channels: ["sms", "chat", "vishing"],
    correctAction: "report_to_authority",
    messageTemplates: ["Pay your overdue penalty of {amount} now or we will contact all your contacts at {domain}.",
    "Your loan penalty is {amount}. Pay now at {domain} or your contacts are notified.",
    "Final notice: settle {amount} today to avoid escalation."],
    questionTemplates: ["A lender threatens to contact everyone. What do you do?"],
    optionTemplates: {
      correct: ["Do not pay. Report the harassment to DTI or CICC."],
      wrong: ["Pay the penalty so they stop.", "Send {amount} to make them wait.", "Reply to negotiate."],
    },
    correctFeedback: ["Correct. Loan-app harassment is illegal; report it instead of paying a stranger."],
    wrongFeedback: ["Paying a stranger never stops the threats; report it to the authorities."],
    archetypes: ["trap"],
    difficulties: ["medium", "hard"],
  },
  {
    family: "charity",
    rule: "Donate only through verified official channels.",
    brands: ["ReliefFund", "ChurchAid"],
    channels: ["sms", "chat"],
    correctAction: "verified_channel_only",
    messageTemplates: ["Donate to the typhoon victims! Send {amount} to this number. Every peso helps.",
    "Help our typhoon drive! Every {amount} feeds a family. Send to this number.",
    "This orphanage needs {amount}. Donate now and save a child."],
    questionTemplates: ["A stranger asks for donations. What do you do?"],
    optionTemplates: {
      correct: ["Check if this is a real, verified charity first."],
      wrong: ["Send {amount} to help the victims.", "Share the number so others can donate."],
    },
    correctFeedback: ["Correct. Verify the charity through official channels before giving."],
    wrongFeedback: ["Scammers use disasters to collect 'donations' that go to them, not victims."],
    archetypes: ["trap"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "fake-reward",
    rule: "You cannot win a raffle you never entered.",
    brands: ["PCSO", "GCash", "MallVoucher"],
    channels: ["sms", "email", "chat"],
    correctAction: "ignore_and_report",
    messageTemplates: ["Congratulations! You won {amount}! Claim at {domain} before it expires.",
    "You won {amount} in our anniversary draw! Claim at {domain} today.",
    "Your GCash raffle ticket won! Pay a small fee at {domain} to receive {amount}.",
    "Last day to claim your prize of {amount}! Visit {domain}."],
    questionTemplates: ["You won a raffle you never joined. What do you do?"],
    optionTemplates: {
      correct: ["Ignore it. You never joined, so this is fake."],
      wrong: ["Click the link quickly before the prize expires.", "Forward it to a friend so they can also win.", "Send a small fee to claim the prize."],
    },
    correctFeedback: ["Correct. If you did not join, you cannot win. This is a classic fake-reward scam."],
    wrongFeedback: ["Winners do not pay to claim prizes. You cannot win a raffle you never entered."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "good-message",
    rule: "Real OTP texts exist. The scam is anyone who ASKS you to send the code.",
    brands: ["GCASH", "MAYA", "SHOPEE", "LAZADA"],
    channels: ["sms", "email"],
    correctAction: "recognize_legit",
    messageTemplates: [
      "{sender}: Your verification code is 4126. Do not share this code with anyone. {sender} will never ask for it.",
      "{sender}: Your order has been shipped. Track it in the app.",
      "{sender}: Thank you for your cash-in of {amount}. Your new balance is available in the app.",
    ],
    questionTemplates: ["This looks like a real message. Is it a scam?", "A message from a company you use. What do you do?"],
    optionTemplates: {
      correct: ["This is real. It is from the official sender and does not ask me to send anything."],
      wrong: ["This is a scam because it mentions a code.", "Block and report it.", "Reply to confirm my identity."],
    },
    correctFeedback: ["Correct. A real OTP text tells you to keep it secret; the scam is anyone who ASKS you to send it."],
    wrongFeedback: ["Flagging every real message makes you distrust everything. The test is whether anyone ASKS you to act."],
    archetypes: ["good-message"],
    difficulties: ["medium", "hard"],
  },
];

export const getTemplate = (family: ScenarioFamily): TemplateFamily | undefined =>
  TEMPLATE_FAMILIES.find((t) => t.family === family);
