// === DOJO LOCALIZED TEMPLATES ===
// Per-language copies of the English template families (dojo-templates.ts).
// Slot placeholders ({sender} {brand} {amount} {domain} {urg} {official} {action})
// are preserved verbatim - the generator fills them the same way in every
// language. Each language keeps the SAME template count + slot order so the
// seeded generator produces structurally identical scenarios, just localized.
//
// Keys that are proper nouns or machine values (brands, channels, archetypes,
// correctAction, difficulties) are intentionally NOT translated.

import { TemplateFamily } from "./dojo-templates";

// Localized slot pools. amounts/fakeDomains/senderLabels are language-neutral
// (currency, domains, brand names); urgencyTriggers + victimProfiles are
// user-facing sentences and ARE translated.
export const POOLS_TAGALOG = {
  amounts: ["P150", "P250", "P500", "P1,500", "P2,000", "P5,000", "P8,000", "P12,000", "P25,000", "P45,000", "P100,000", "P1,000,000"],
  fakeDomains: [
    "g-cash-verify-ph.top",
    "bdo-secure-login-verify.top",
    "jnt-tracking-ph.site",
    "maya-security-alert.xyz",
    "pagibig-loan-release.site",
    "bit.ly/verify-now",
    "gcash-update.ph-verify.top",
    "smart-rewar-ds.top",
    "shopee-refund-ph.site",
    "gov-ph-tax.site",
  ],
  urgencyTriggers: [
    "naka-lock ang account mo",
    "mawawala ang pera mo sa loob ng 24 oras",
    "ito na ang huling pagkakataon mo",
    "may na-file na case number laban sa iyo",
    "ibabalik ang parcel mo",
    "ikakansela ang benefits mo",
    "may nakitang unauthorized transfer",
    "ide-deactivate ang SIM mo",
  ],
  victimProfiles: [
    "Lola sa probinsya",
    "kolehiyala sa Maynila",
    "OFW sa Riyadh",
    "may-ari ng sari-sari store",
    "driver ng jeepney",
    "call-center agent",
    "senior pensioner",
    "maliit na online seller",
  ],
  senderLabels: {
    GCASH: "GCash", MAYA: "Maya", GOTYME: "GoTyme", SHOPEEPAY: "ShopeePay",
    BDO: "BDO Alerts", BPI: "BPI", METROBANK: "Metrobank", UNIONBANK: "UnionBank",
    RCBC: "RCBC", LANDBANK: "LandBank", PNB: "PNB", SECURITY_BANK: "Security Bank",
    GLOBE: "Globe", SMART: "Smart", DITO: "DITO", PLDT: "PLDT Home",
    JNT: "J&T Express", LBC: "LBC", NINJAVAN: "Ninja Van", FLASH: "Flash Express",
    SHOPEE: "Shopee", LAZADA: "Lazada", BIR: "BIR", SSS: "SSS", PAGIBIG: "Pag-IBIG",
    PHILHEALTH: "PhilHealth", NBI: "NBI", PNP: "PNP-ACG", CICC: "CICC",
  },
};

const TL_BRANDS_EN: TemplateFamily[] = [];

export const TEMPLATE_FAMILIES_TAGALOG: TemplateFamily[] = [
  {
    family: "ewallet",
    rule: "Lihim ang OTP. HINDI hihingi ng OTP ang totoong kumpanya.",
    brands: ["GCASH", "MAYA", "GOTYME", "SHOPEEPAY"],
    channels: ["sms", "email", "chat", "vishing"],
    correctAction: "verify_in_official_app",
    messageTemplates: [
      "{sender}: {urg} I-reply ang OTP mo ngayon para ma-reactivate, o mawawala ang pera mo sa loob ng 24 oras.",
      "{sender} Alerto: {urg}. I-verify sa {domain} o masususpend ang account mo.",
      "{sender}: May papasok na transfer na {amount}! Magbayad muna ng maliit na release fee para matanggap ito.",
      "{sender}: Nakita namin ang kahina-hinalang login sa account mo. I-verify ngayon sa {domain} o ilo-lock ito.",
      "{sender}: Mag-e-expire ang MPIN mo ngayon. I-update ito sa {domain} para magamit pa ang wallet mo.",
      "{sender}: Error sa double refund! Para i-correct, kumpirmahin ang account mo sa {domain} sa loob ng 24 oras.",
    ],
    questionTemplates: ["May mensaheng nagsasabing {urg} at humihingi ng OTP. Ano ang gagawin mo?", "May text na sabi dapat kumilos ka agad. Ano ang gagawin mo?"],
    optionTemplates: {
      correct: ["Buksan ang totoong {brand} app at i-check ang account ko."],
      wrong: ["I-reply ang OTP agad para ligtas ang pera ko.", "Tawagan ang numero sa text para ma-verify.", "Bayaran ang release fee para matanggap ko ang transfer."],
    },
    correctFeedback: ["Tama. In-check mo ang totoong {brand} app imbes na maniwala sa text. Ang account mo ang source of truth, hindi ang mensahe."],
    wrongFeedback: [
      "Hindi humihingi ng OTP ang totoong {brand}. Ang mensaheng iyan ang scam.",
      "Ang numero na iyan ay sa scammer. Gamitin lamang ang opisyal na {official}.",
      "Kung magbabayad ka para makatanggap ng pera, scam iyan.",
    ],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "bank",
    rule: "Walang bangkong humihingi ng OTP o card code mo.",
    brands: ["BDO", "BPI", "METROBANK", "UNIONBANK", "RCBC", "LANDBANK", "PNB", "SECURITY_BANK"],
    channels: ["email", "sms", "vishing"],
    correctAction: "call_official_hotline",
    messageTemplates: [
      "{sender}: {urg}. I-click ang {domain} para i-verify ang identity mo ngayon.",
      "{sender} Fraud Dept: may nakitang unauthorized transfer na {amount}. I-reply ang card details mo para ma-reverse.",
      "{sender}: Naka-hold ang account mo para sa review. I-kumpirma ang identity mo sa {domain} para maibalik ang access.",
      "{sender} Security: May bagong device na nag-try mag-login. I-approve o i-decline sa {domain}.",
      "{sender}: Isasara ang card mo dahil sa inactivity. I-reactivate sa {domain}.",
    ],
    questionTemplates: ["May email na nagsasabing nasa panganib ang account mo. Ano ang gagawin mo?", "Sabi ng tumatawag ginamit ang card mo sa fraud. Ano ang gagawin mo?"],
    optionTemplates: {
      correct: ["Ibaba ang tawag, tapos tawagan ang numero sa likod ng card ko.", "Buksan ang bank app ko at i-check kung may totoong alert."],
      wrong: ["Basa-hin ang card number ko at 3-digit code para itigil ang fraud.", "I-click ang link at ilagay ang login ko para hindi maisara ang account.", "Basa-hin ang code na pinadala nila."],
    },
    correctFeedback: ["Tama. Pwedeng peke ang caller ID at sender name. Laging tawagan ang totoong {official} number mismo."],
    wrongFeedback: ["Huwag magbigay ng card details o code sa phone o text link. Alam na ng totoong bangko ang card number mo."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "telco",
    rule: "Hindi humihingi ang telco ng OTP o ID mo sa text.",
    brands: ["GLOBE", "SMART", "DITO", "PLDT"],
    channels: ["sms", "chat"],
    correctAction: "verify_in_official_app",
    messageTemplates: [
      "{sender}: Mag-e-expire na ang points mo! I-redeem ang {amount} ngayon sa {domain}.",
      "{sender}: {urg} I-reply ang registered name at address mo para manatiling active ang line mo.",
      "{sender}: Malapit nang mag-expire ang account mo. I-renew sa {domain} para mapanatili ang number mo.",
      "{sender}: Libreng {amount} load para sa iyo! I-claim sa {domain} ngayon.",
      "{sender}: Overdue na ang bill mo. Bayaran ang {amount} sa {domain} para maiwasan ang disconnection.",
    ],
    questionTemplates: ["May mensaheng nag-aalok ng points o nagbabala sa line mo. Ano ang gagawin mo?"],
    optionTemplates: {
      correct: ["Buksan ang opisyal na {brand} app at i-check doon."],
      wrong: ["I-click ang link at ilagay ang details ko para mag-redeem.", "I-reply ang buong pangalan at address ko.", "Tawagan ang numero sa text."],
    },
    correctFeedback: ["Tama. I-check ang opisyal na {brand} app; huwag magtiwala sa text link."],
    wrongFeedback: ["Ang pag-reply o pag-click ay nagsasabi sa scammer na active ang numero at details mo."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "delivery",
    rule: "Bayad ang delivery fee sa totoong app o sa pinto, hindi sa text link.",
    brands: ["JNT", "LBC", "NINJAVAN", "FLASH"],
    channels: ["sms", "chat"],
    correctAction: "compare_tracking",
    messageTemplates: [
      "{sender}: Naka-hold ang parcel mo para sa unpaid fee na {amount}. Bayaran sa {domain} o ibabalik ang package mo.",
      "{sender}: {urg} Para ma-reschedule ang delivery, magbayad ng maliit na fee sa {domain}.",
      "{sender}: Na-attempt ang delivery pero pumalpak. I-reschedule sa {domain} para sa {amount}.",
      "{sender}: Kailangan ng package mo ng maliit na storage fee na {amount}. Bayaran sa {domain}.",
      "{sender}: Hindi kumpleto ang address mo. I-confirm sa {domain} o ibabalik ang parcel.",
    ],
    questionTemplates: ["May mensaheng nagsasabing naka-hold ang parcel mo. Ano ang gagawin mo?"],
    optionTemplates: {
      correct: ["I-check muna ang totoong tracking number sa order app ko."],
      wrong: ["Bayaran ang fee para hindi maibalik ang parcel ko.", "Magbayad sa link para ligtas.", "Mag-reply para mag-confirm."],
    },
    correctFeedback: ["Tama. Ikinumpara mo sa totoong tracking ng order mo. Kung hindi tugma, peke iyan."],
    wrongFeedback: ["Kinokolekta ng totoong courier ang fee sa pinto o sa opisyal na app, hindi sa random text link."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "customs",
    rule: "Hindi naniningil ng fee ang customs sa text.",
    brands: ["LBC", "PHILPOST"],
    channels: ["sms", "email"],
    correctAction: "call_official_hotline",
    messageTemplates: [
      "{sender}: Naka-hold sa customs ang package mo. Bayaran ang {amount} clearance fee sa {domain} para ma-release.",
      "{sender} Customs: Naka-pending sa inspection ang international parcel mo. Bayaran ang {amount} inspection fee sa {domain}.",
      "{sender}: May nahanap na undeclared items ang customs. I-clear sa {domain} para sa {amount}.",
    ],
    questionTemplates: ["May gusto ang customs na clearance fee. Ano ang gagawin mo?"],
    optionTemplates: {
      correct: ["Tawagan ang opisyal na hotline ng {sender} para i-check kung totoo."],
      wrong: ["Bayaran ang fee para ma-release ng customs ang package ko.", "Mag-reply para mag-confirm."],
    },
    correctFeedback: ["Tama. Nag-verify ka sa opisyal na channel. Peke ang text na customs scam."],
    wrongFeedback: ["Hindi naniningil ng fee ang customs sa text, at kung wala ka namang pinadala mula abroad, wala nang icle-clear."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "job",
    rule: "Ang trabahong magbabayad KA para magtrabaho ay hindi trabaho, scam iyan.",
    brands: ["CryptoGlobal", "RemoteHire", "DataEntryPH"],
    channels: ["linkedin", "chat", "email"],
    correctAction: "never_pay_to_work",
    messageTemplates: [
      "Gusto namin ang profile mo! {amount}/buwan, work from home. I-download ang app na ito para magsimula sa training ngayon.",
      "Unang task mo: i-transfer ang {amount} bilang refundable performance deposit.",
      "Congratulations! Pumasa ka sa screening namin. Bayaran ang {amount} processing fee sa {domain} para magsimula.",
      "HR dito: halos tapos na ang onboarding mo. Kumpirmahin sa {domain} para sa {amount} refundable deposit.",
      "Nasa shortlist ka! I-confirm ang slot mo sa {domain} sa loob ng 24 oras.",
    ],
    questionTemplates: ["May pangarap na trabaho na unang nakahanap sa iyo. Ano ang gagawin mo?", "Gusto nila ng deposit para magsimula sa trabaho. Ano ang gagawin mo?"],
    optionTemplates: {
      correct: ["I-search ang pangalan ng kumpanya at i-check ang totoong website nila.", "Hindi. Walang totoong trabaho na hihingi ng bayad para magtrabaho."],
      wrong: ["I-download agad ang app bago pa pumili ng iba.", "Ipadala ang deposit. Sabi nila refundable.", "Ipadala ang kalahati at humingi ng proof."],
    },
    correctFeedback: ["Tama. May verifiable web presence ang totoong kumpanya; hindi sila nagmamadali na mag-install ng app o magbayad ng deposit."],
    wrongFeedback: ["Bayaran KA ng totoong employer. Hindi sila hihingi ng bayad para magsimula ka."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "romance",
    rule: "Huwag magpadala ng pera sa taong hindi mo pa nakikita nang personal.",
    brands: ["DatingApp"],
    channels: ["chat", "vishing"],
    correctAction: "never_send_to_stranger",
    messageTemplates: [
      "Mahal kita pero naka-stuck ako sa customs at kailangan ko ng {amount} para makita kita. Pwede bang ipadala?",
      "Kailangan ng crypto investment ko ng {amount} pa para ma-withdraw, tapos babayaran kita.",
      "Nasa problema ako sa airport. Kailangan nila ng {amount} para ma-release ang visa ko. Ipadala na ngayon.",
      "Nag-invest ako para sa atin, pero kailangan ko ng {amount} pa para ma-withdraw at pumunta sa iyo.",
      "Na-freeze ang account ko. Pwede mo bang i-hold ang {amount} para sa akin hanggang makarating ako?",
    ],
    questionTemplates: ["May taong nakilala mo online na nangangailangan ng pera ngayon. Ano ang gagawin mo?"],
    optionTemplates: {
      correct: ["Hindi. Hindi ko pa nakikita ang taong ito nang personal."],
      wrong: ["Ipadala ang pera para hindi sila ma-stuck.", "Humingi muna ng proof, tapos ipadala.", "Ipadala ang kalahati ngayon."],
    },
    correctFeedback: ["Tama. Bumubuo ng tiwala ang romance scammer para humingi ng pera. Huwag magpadala ng pera sa hindi mo pa nakikilala."],
    wrongFeedback: ["Maganda ang paghingi ng proof, pero ang tanging ligtas na sagot ay huwag magpadala ng pera sa estranghero."],
    archetypes: ["trap", "redirect"],
    difficulties: ["medium", "hard"],
  },
  {
    family: "investment",
    rule: "Ang 'sure profit' na hindi mo hiniling ay palaging scam.",
    brands: ["Binance", "SureKita", "CryptoPips"],
    channels: ["chat", "email", "sms"],
    correctAction: "ignore_and_report",
    messageTemplates: [
      "Garantisadong kita! Mag-invest ng {amount} ngayon, doblehin sa isang linggo. Sure kita, pasok na!",
      "Dinoble ng AI trading app namin ang {amount} sa isang buwan. Magsimula na.",
      "Dinoble ng app namin ang {amount} sa 7 araw. Simulan ang account mo ngayon sa {domain}.",
      "Signal group: garantisadong {amount} payout sa linggong ito. Sumali bago magsara.",
      "Kumita ng {amount} araw-araw na walang risk. Mag-withdraw anytime. Mag-invest ngayon.",
    ],
    questionTemplates: ["May nangangako ng garantisadong kita. Ano ang gagawin mo?"],
    optionTemplates: {
      correct: ["I-ignore at i-report. Walang garantisadong kita."],
      wrong: ["Mag-invest ng {amount} para subukan.", "Magsimula sa maliit para i-test.", "I-share sa pamilya para kumita rin sila."],
    },
    correctFeedback: ["Tama. Ang 'garantisadong kita' ang pinakamalakas na scam signal na mayroon."],
    wrongFeedback: ["Ang sinumang nangangako ng garantisadong kita ay kukunin ang pera mo, hindi i-invest."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "government",
    rule: "Walang opisina ng gobyerno na humihingi ng fee o OTP sa text.",
    brands: ["BIR", "SSS", "PAGIBIG", "PHILHEALTH", "NBI", "PNP", "CICC"],
    channels: ["sms", "email", "vishing"],
    correctAction: "call_official_hotline",
    messageTemplates: [
      "{sender}: {urg} Bayaran ang penalty mong {amount} sa {domain} para maiwasan ang case filing.",
      "{sender}: Ikakansela ang benefits mo maliban kung mag-verify ka sa {domain}.",
      "{sender}: Handa na ang tax refund mong {amount}. I-claim sa {domain} bago mag-expire.",
      "{sender}: I-update ang records mo sa {domain} o i-pause ang pension mo.",
      "{sender}: May warrant na inilabas laban sa ID mo. I-resolve sa {domain} para maiwasan ang pag-aresto.",
    ],
    questionTemplates: ["May opisina ng gobyerno na nagbabanta ng penalty sa text. Ano ang gagawin mo?"],
    optionTemplates: {
      correct: ["Tawagan ang opisyal na hotline ng {sender} para i-verify."],
      wrong: ["Bayaran ang penalty para maiwasan ang kaso.", "I-click ang link at ilagay ang details ko.", "Tawagan ang numero sa text."],
    },
    correctFeedback: ["Tama. Hindi naniningil ang gobyerno ng fee sa text; tawagan ang opisyal na numero."],
    wrongFeedback: ["May opisyal na channel ang mga ahensya tulad ng {sender}. Impersonation ang text."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "quishing",
    rule: "Kahina-hinala ang QR code na hindi mo hiniling.",
    brands: ["ParkingPH", "MerchantQR"],
    channels: ["qr"],
    correctAction: "use_official_payment",
    messageTemplates: ["[QR] I-scan para bayaran ang {amount} parking fee. Instant at secure ang payment.",
      "[QR] I-scan para bayaran ang electric bill mo. Official partner. {amount} ang bayad.",
      "[QR] Bayaran dito ang food delivery mo. Mabilis at secure.",
      "[QR] I-verify ang parking exit mo sa pag-scan ng code na ito."],
    questionTemplates: ["May QR code na nag-aalok magbayad ng parking. Ano ang gagawin mo?"],
    optionTemplates: {
      correct: ["Hanapin ang opisyal na parking sign o magbayad sa machine."],
      wrong: ["I-scan at magbayad. {amount} lang naman.", "I-scan pero i-check ang page bago magbayad."],
    },
    correctFeedback: ["Tama. Laging gamitin ang opisyal na paraan ng pagbayad, hindi ang sticker na biglang lumitaw."],
    wrongFeedback: ["Maaaring tumuturo ang QR na iyon sa pekeng payment page na magnanakaw ng card mo."],
    archetypes: ["trap"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "vishing",
    rule: "Pwedeng peke ang Caller ID. Ibaba ang tawag at tawagan ang opisyal na numero.",
    brands: ["BDO", "BPI", "GLOBE", "SMART", "CICC"],
    channels: ["vishing"],
    correctAction: "hang_up_call_official",
    messageTemplates: [
      "Ito ang {sender} fraud department. Ginamit ang card mo para sa {amount}. Sabihin ang card number at code sa likod.",
      "Kailangan nating i-secure ang account mo NGAYON. Magpapadala ako ng code. Pakibasa pabalik.",
      "Ito ang {sender} tech support. Na-hack ang line mo. Ibigay ang code sa phone mo.",
      "Tumatawag ako mula sa {sender}. May nag-try na i-access ang account mo. I-confirm ang details mo.",
      "{sender} agent dito. Para ma-reverse ang fraudulent transfer, kailangan ko ang OTP mo.",
    ],
    questionTemplates: ["Ipinapakita ng caller ID ang totoong bangko mo. Ano ang gagawin mo?"],
    optionTemplates: {
      correct: ["Ibaba ang tawag, tapos tawagan ang numero sa likod ng card ko."],
      wrong: ["Basa-hin ang card number ko para itigil ang fraud.", "Basa-hin pabalik ang code na pinadala nila.", "Humingi muna ng proof kung sino sila."],
    },
    correctFeedback: ["Tama. Pwedeng peke ang caller ID. Ibaba ang tawag at tawagan ang totoong numero."],
    wrongFeedback: ["Huwag magbasa ng code o card details sa taong tumawag sa iyo, gaano man ka-official ang dating nila."],
    archetypes: ["trap", "redirect"],
    difficulties: ["medium", "hard"],
  },
  {
    family: "sim-pretext",
    rule: "Mag-register ng SIM sa opisyal na telco channel lamang.",
    brands: ["GLOBE", "SMART", "DITO"],
    channels: ["sms", "chat", "vishing"],
    correctAction: "official_channel_only",
    messageTemplates: ["{sender}: {urg} Mag-re-register sa {domain} o mawawala ang SIM mo.",
      "{sender}: Hindi fully registered ang SIM mo. Kumpletuhin sa {domain} o putulin ang line mo.",
      "{sender}: Kailangan ng bagong SIM rules na mag-verify ka sa {domain} sa loob ng 48 oras."],
    questionTemplates: ["May mensaheng nagsasabing ide-deactivate ang SIM mo. Ano ang gagawin mo?"],
    optionTemplates: {
      correct: ["Buksan ang opisyal na website o app ng {sender} at i-check doon."],
      wrong: ["I-click ang link at ilagay ang ID ko.", "Tawagan ang numero sa text."],
    },
    correctFeedback: ["Tama. Ang SIM registration ay nangyayari lamang sa opisyal na telco channel."],
    wrongFeedback: ["Kinokolekta ng link na iyan ang ID mo. Hindi ka tina-text ng totoong telco para mag-register sa random link."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "family-emergency",
    rule: "Ginagamit ng scammer ang pangalan ng pamilya para takutin ka. Tawagan ang totoong naka-save na numero.",
    brands: ["Child", "Relative"],
    channels: ["sms", "chat", "vishing"],
    correctAction: "call_real_number",
    messageTemplates: [
      "Mom/Dad, ako ito. Nasira ang phone ko. Ipadala ang {amount} sa GCash na ito. Pakiusap huwag tumawag, sira ang phone ko.",
      "Ako ito, ang anak mo. Nasa ospital ako. Kailangan ng ospital ng {amount}. Pakiusap ipadala sa numerong ito.",
      "Lola, may problema ako sa pulis. Kailangan ko ng {amount} para sa piyansa. Huwag sabihin kahit kanino.",
      "Mom, nawala ang wallet ko abroad. Pakiusap ipadala ang {amount} sa account na ito.",
    ],
    questionTemplates: ["Parang eksaktong boses ng anak mo. Ano ang gagawin mo?"],
    optionTemplates: {
      correct: ["Tawagan ang TOTOONG naka-save na numero ng anak ko bago magpadala ng kahit ano."],
      wrong: ["Ipadala ang pera. Anak ko talaga iyan.", "Magtanong ng tanong na alam lang ng anak ko.", "Ipadala ang kalahati ngayon."],
    },
    correctFeedback: ["Tama. Nag-verify ka bago kumilos. Huwag magtiwala sa hindi kilalang 'bagong numero'."],
    wrongFeedback: ["Ang 'huwag tumawag' na hiling ang red flag; ginagamit ito ng scammer para pigilan kang mag-verify."],
    archetypes: ["trap"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    family: "remittance",
    rule: "Hindi ka nagbabayad ng fee para makatanggap ng remittance.",
    brands: ["WesternUnion", "Palawan", "Remitly"],
    channels: ["sms", "chat", "email"],
    correctAction: "never_pay_to_receive",
    messageTemplates: ["Naka-hold ang remittance mong {amount}. Bayaran ang release fee sa {domain} para matanggap ito.",
      "Naghihintay ang remittance mong {amount}, pero dapat kang magbayad ng {amount} release fee muna sa {domain}.",
      "Palawan: I-claim ang pera mo. I-confirm sa {domain} para ma-release ang {amount}."],
    questionTemplates: ["May mensaheng nagsasabing kailangan ng remittance mo ng fee. Ano ang gagawin mo?"],
    optionTemplates: {
      correct: ["I-check ang remittance app ko o ang opisyal na branch mismo."],
      wrong: ["Bayaran ang release fee para makuha ko ang pera.", "Mag-reply para mag-confirm.", "Magpatulong sa kaibigan na bayaran."],
    },
    correctFeedback: ["Tama. Dumarating mag-isa ang totoong transfer; walang kailangan magbayad para makatanggap ng pera."],
    wrongFeedback: ["Ang pagbabayad para makatanggap ng pera ay ang advance-fee trick: magbabayad ka, hindi darating ang pera."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "loan-app",
    rule: "Hindi naniningil ng penalty ang totoong lender sa pamamagitan ng estranghero.",
    brands: ["LendFast", "CashKo"],
    channels: ["sms", "chat", "vishing"],
    correctAction: "report_to_authority",
    messageTemplates: ["Bayaran ang overdue penalty mong {amount} ngayon o kokontakin namin ang lahat ng contacts mo sa {domain}.",
      "Ang loan penalty mo ay {amount}. Bayaran ngayon sa {domain} o ma-notify ang contacts mo.",
      "Final notice: bayaran ang {amount} ngayon para maiwasan ang escalation."],
    questionTemplates: ["May lender na nagbabanta na kontakin ang lahat. Ano ang gagawin mo?"],
    optionTemplates: {
      correct: ["Huwag magbayad. I-report ang harassment sa DTI o CICC."],
      wrong: ["Bayaran ang penalty para tumigil sila.", "Ipadala ang {amount} para maghintay sila.", "Mag-reply para mag-negotiate."],
    },
    correctFeedback: ["Tama. Illegal ang loan-app harassment; i-report ito imbes na magbayad sa estranghero."],
    wrongFeedback: ["Ang pagbabayad sa estranghero ay hindi tumitigil sa mga banta; i-report ito sa awtoridad."],
    archetypes: ["trap"],
    difficulties: ["medium", "hard"],
  },
  {
    family: "charity",
    rule: "Mag-donate lamang sa na-verify na opisyal na channel.",
    brands: ["ReliefFund", "ChurchAid"],
    channels: ["sms", "chat"],
    correctAction: "verified_channel_only",
    messageTemplates: ["Mag-donate sa mga biktima ng bagyo! Ipadala ang {amount} sa numerong ito. Bawat piso ay nakakatulong.",
      "Tulungan ang typhoon drive namin! Bawat {amount} ay nagpapakain ng pamilya. Ipadala sa numerong ito.",
      "Kailangan ng orphanage na ito ng {amount}. Mag-donate ngayon at iligtas ang isang bata."],
    questionTemplates: ["May estranghero na humihingi ng donasyon. Ano ang gagawin mo?"],
    optionTemplates: {
      correct: ["I-check muna kung totoo at na-verify ang charity."],
      wrong: ["Ipadala ang {amount} para matulungan ang mga biktima.", "I-share ang numero para makapag-donate ang iba."],
    },
    correctFeedback: ["Tama. I-verify ang charity sa pamamagitan ng opisyal na channel bago magbigay."],
    wrongFeedback: ["Ginagamit ng scammer ang disaster para mangolekta ng 'donasyon' na sa kanila napupunta, hindi sa biktima."],
    archetypes: ["trap"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "fake-reward",
    rule: "Hindi ka maaaring manalo sa raffle na hindi mo sinalihan.",
    brands: ["PCSO", "GCash", "MallVoucher"],
    channels: ["sms", "email", "chat"],
    correctAction: "ignore_and_report",
    messageTemplates: ["Congratulations! Nanalo ka ng {amount}! I-claim sa {domain} bago mag-expire.",
      "Nanalo ka ng {amount} sa anniversary draw namin! I-claim sa {domain} ngayon.",
      "Nanalo ang GCash raffle ticket mo! Magbayad ng maliit na fee sa {domain} para matanggap ang {amount}.",
      "Huling araw para i-claim ang premyo mong {amount}! Bisitahin ang {domain}."],
    questionTemplates: ["Nanalo ka sa raffle na hindi mo sinalihan. Ano ang gagawin mo?"],
    optionTemplates: {
      correct: ["I-ignore ito. Hindi ka sumali, kaya peke ito."],
      wrong: ["I-click agad ang link bago mag-expire ang premyo.", "I-forward sa kaibigan para manalo rin sila.", "Magpadala ng maliit na fee para i-claim ang premyo."],
    },
    correctFeedback: ["Tama. Kung hindi ka sumali, hindi ka mananalo. Ito ang klasikong fake-reward scam."],
    wrongFeedback: ["Hindi nagbabayad ang mananalo para i-claim ang premyo. Hindi ka maaaring manalo sa raffle na hindi mo sinalihan."],
    archetypes: ["trap", "redirect"],
    difficulties: ["easy", "medium"],
  },
  {
    family: "good-message",
    rule: "Umiiral ang totoong OTP text. Ang scam ay ang sinumang nagtatanong sa iyo na IPADALA ang code.",
    brands: ["GCASH", "MAYA", "SHOPEE", "LAZADA"],
    channels: ["sms", "email"],
    correctAction: "recognize_legit",
    messageTemplates: [
      "{sender}: Ang verification code mo ay 4126. Huwag ibahagi ang code na ito kanino man. Hindi ito hihingiin ng {sender}.",
      "{sender}: Na-ship na ang order mo. I-track sa app.",
      "{sender}: Salamat sa cash-in mong {amount}. Available na ang bagong balance mo sa app.",
    ],
    questionTemplates: ["Parang totoong mensahe ito. Scam ba?", "May mensahe mula sa kumpanyang ginagamit mo. Ano ang gagawin mo?"],
    optionTemplates: {
      correct: ["Totoo ito. Galing sa opisyal na sender at hindi humihingi ng ipapadala."],
      wrong: ["Scam ito dahil binanggit nito ang code.", "I-block at i-report.", "Mag-reply para i-confirm ang identity ko."],
    },
    correctFeedback: ["Tama. Sinasabi sa iyo ng totoong OTP text na itago ito; ang scam ay ang sinumang NAGTATANONG na ipadala ito."],
    wrongFeedback: ["Ang pag-flag sa bawat totoong mensahe ay magtitiwala ka sa wala. Ang test ay kung may NAGTATANONG sa iyo na kumilos."],
    archetypes: ["good-message"],
    difficulties: ["medium", "hard"],
  },
];

void TL_BRANDS_EN;
