// scripts/generate-scenarios.ts - builds and commits the 500-scenario library.
// Run: npx tsx scripts/generate-scenarios.ts
// Emits src/dojo/scenarios.generated.ts exporting GENERATED_SCENARIOS and
// ALL_SCENARIOS. Exits nonzero on any pedagogy-contract violation.

import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { generateScenarios, validateLibrary } from "../src/dojo/generator";
import { SCENARIOS } from "../src/dojo/scenarios";

const __dirname = dirname(fileURLToPath(import.meta.url));

const generated = generateScenarios({ perFamily: 500, seed: 20260806 });
const violations = validateLibrary([...SCENARIOS, ...generated]);

if (violations.length > 0) {
  console.error(`VALIDATION FAILED: ${violations.length} violation(s)`);
  for (const v of violations.slice(0, 20)) console.error(`  - ${v}`);
  process.exit(1);
}

const body = `// AUTO-GENERATED by scripts/generate-scenarios.ts - do not edit by hand.
// Regenerate: npx tsx scripts/generate-scenarios.ts
import { Scenario } from "./scenarios";
import { SCENARIOS } from "./scenarios";

export const GENERATED_SCENARIOS: Scenario[] = ${JSON.stringify(generated, null, 2)};

export const ALL_SCENARIOS: Scenario[] = [...SCENARIOS, ...GENERATED_SCENARIOS];
`;

const out = join(__dirname, "../src/dojo/scenarios.generated.ts");
writeFileSync(out, body);

// Summary
const byFamily: Record<string, number> = {};
const byDifficulty: Record<string, number> = {};
for (const s of generated) {
  byFamily[s.family] = (byFamily[s.family] || 0) + 1;
  byDifficulty[s.difficulty] = (byDifficulty[s.difficulty] || 0) + 1;
}
console.log(`Generated ${generated.length} scenarios (${SCENARIOS.length} curated + ${generated.length} generated = ${generated.length + SCENARIOS.length} total)`);
console.log("By difficulty:", JSON.stringify(byDifficulty));
console.log("By family:", JSON.stringify(byFamily, null, 2));
console.log("Validation: clean. Written to", out);
