// scripts/generate-scenarios.ts - builds and commits the scenario library in
// all 4 supported languages.
// Run: npx tsx scripts/generate-scenarios.ts
// Emits:
//   src/dojo/scenarios.generated.ts        (ENGLISH: curated + generated)
//   src/dojo/scenarios.generated.tl.ts     (TAGALOG generated)
//   src/dojo/scenarios.generated.ceb.ts    (BISAYA generated)
//   src/dojo/scenarios.generated.ilo.ts    (ILOCANO generated)
// Each localized file exports ALL_SCENARIOS_<LANG>. Exits nonzero on any
// pedagogy-contract violation.

import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { generateScenarios, validateLibrary } from "../src/dojo/generator";
import { SCENARIOS } from "../src/dojo/scenarios";

const __dirname = dirname(fileURLToPath(import.meta.url));
const LANGS = ["ENGLISH", "TAGALOG", "BISAYA", "ILOCANO"] as const;

const generated: Record<string, ReturnType<typeof generateScenarios>> = {};
for (const lang of LANGS) {
  generated[lang] = generateScenarios({ perFamily: 500, seed: 20260806, lang });
  // Validate every language: generated scenarios must pass the pedagogy contract.
  const violations = validateLibrary(generated[lang]);
  if (violations.length > 0) {
    console.error(`VALIDATION FAILED (${lang}): ${violations.length} violation(s)`);
    for (const v of violations.slice(0, 20)) console.error(`  - ${v}`);
    process.exit(1);
  }
}

const enBody = `// AUTO-GENERATED by scripts/generate-scenarios.ts - do not edit by hand.
// Regenerate: npx tsx scripts/generate-scenarios.ts
import { Scenario } from "./scenarios";
import { SCENARIOS } from "./scenarios";

export const GENERATED_SCENARIOS: Scenario[] = ${JSON.stringify(generated.ENGLISH, null, 2)};

export const ALL_SCENARIOS: Scenario[] = [...SCENARIOS, ...GENERATED_SCENARIOS];
`;
writeFileSync(join(__dirname, "../src/dojo/scenarios.generated.ts"), enBody);

const locBodies: Record<string, string> = {
  TAGALOG: `// AUTO-GENERATED - TAGALOG - do not edit by hand. Regenerate: npx tsx scripts/generate-scenarios.ts
import { Scenario } from "./scenarios";

export const ALL_SCENARIOS_TAGALOG: Scenario[] = ${JSON.stringify(generated.TAGALOG, null, 2)};
`,
  BISAYA: `// AUTO-GENERATED - BISAYA - do not edit by hand. Regenerate: npx tsx scripts/generate-scenarios.ts
import { Scenario } from "./scenarios";

export const ALL_SCENARIOS_BISAYA: Scenario[] = ${JSON.stringify(generated.BISAYA, null, 2)};
`,
  ILOCANO: `// AUTO-GENERATED - ILOCANO - do not edit by hand. Regenerate: npx tsx scripts/generate-scenarios.ts
import { Scenario } from "./scenarios";

export const ALL_SCENARIOS_ILOCANO: Scenario[] = ${JSON.stringify(generated.ILOCANO, null, 2)};
`,
};
writeFileSync(join(__dirname, "../src/dojo/scenarios.generated.tl.ts"), locBodies.TAGALOG);
writeFileSync(join(__dirname, "../src/dojo/scenarios.generated.ceb.ts"), locBodies.BISAYA);
writeFileSync(join(__dirname, "../src/dojo/scenarios.generated.ilo.ts"), locBodies.ILOCANO);

// Summary
const byFamily: Record<string, number> = {};
for (const s of generated.ENGLISH) {
  byFamily[s.family] = (byFamily[s.family] || 0) + 1;
}
console.log(`Generated per language: ${Object.fromEntries(LANGS.map((l) => [l, generated[l].length]))}`);
console.log(`ENGLISH total: ${generated.ENGLISH.length + SCENARIOS.length} (${SCENARIOS.length} curated + ${generated.ENGLISH.length} generated)`);
console.log("By family:", JSON.stringify(byFamily));
console.log("Validation: clean (all 4 languages).");
